// Command fairy wires the Wails v3 desktop shell.
//
// Layout follows the Go skill (domain packages, one level deep):
//
//	fairy/
//	  main.go          # wiring only
//	  windows.go       # companion + control-panel adapters
//	  tray.go          # system tray
//	  character/ companion/ config/ desktop/ memory/ model/ profile/ secret/ visual/
//	  assets/          # synced web dist + tray icon for go:embed (not source)
//	  frontend/bindings/  # generated by wails3
package main

import (
	"io/fs"
	"log"
	"os"
	"path/filepath"

	"fairy/character"
	"fairy/companion"
	"fairy/config"
	"fairy/desktop"
	"fairy/memory"
	"fairy/model"
	"fairy/notify"
	"fairy/profile"
	"fairy/visual"
	"github.com/wailsapp/wails/v3/pkg/application"
)

func main() {
	assets, err := fs.Sub(embeddedAssets, "assets/dist")
	if err != nil {
		log.Fatal(err)
	}

	configRoot := os.Getenv("FAIRY_CONFIG_ROOT")
	if configRoot == "" {
		configRoot = filepath.Join(os.Getenv("HOME"), "Library", "Application Support", "dev.rinai.fairy", "harness", "v1")
	}

	bootstrap := desktop.NewBootstrapService(desktop.BootstrapOptions{
		AppName:                "FAIRY",
		MigrationStage:         "wails3-only",
		WailsVersion:           "v3.0.0-alpha2.117",
		RespondRuntimeMigrated: true,
	})
	memoryPath, err := memory.DatabasePath(configRoot)
	if err != nil {
		log.Fatal(err)
	}
	memoryStore, err := memory.OpenOrCreate(memoryPath)
	if err != nil {
		log.Fatal(err)
	}
	modelService := model.NewModelService(configRoot)
	desktopService := desktop.NewDesktopService()
	companionService := companion.NewCompanionServiceWithRuntime(configRoot, memoryStore, modelService)
	defer companionService.Close()

	app := application.New(application.Options{
		Name:        "FAIRY",
		Description: "Desktop companion app with a Go/Wails migration runtime.",
		Icon:        appIcon,
		Services: []application.Service{
			application.NewService(bootstrap),
			application.NewService(character.NewCharacterService(configRoot)),
			application.NewService(config.NewConfigService(configRoot)),
			application.NewService(desktopService),
			application.NewService(modelService),
			application.NewService(companionService),
			application.NewService(memory.NewMemoryServiceWithStore(configRoot, memoryStore)),
			application.NewService(profile.NewProfileService(configRoot)),
			application.NewService(visual.NewVisualService(configRoot)),
			application.NewServiceWithOptions(visual.NewAssetHandler(configRoot), application.ServiceOptions{
				Name:  "CharacterAssetHandler",
				Route: "/fairy-character",
			}),
		},
		Assets: application.AssetOptions{
			Handler: application.AssetFileServerFS(assets),
		},
		Mac: application.MacOptions{
			ApplicationShouldTerminateAfterLastWindowClosed: false,
		},
	})

	companion.AttachEventEmitter(companionService, func(event companion.HarnessEvent) {
		app.Event.Emit("companion-harness-event", event)
	})
	desktop.AttachStateEmitter(desktopService, func(state desktop.DesktopState) {
		app.Event.Emit("desktop-state-changed", state)
	})
	notify.AttachConfigEmitter(func(change notify.ConfigurationChange) {
		app.Event.Emit("companion-configuration-changed", change)
	})

	attachProductWindows(app, desktopService)
	setupSystemTray(app, desktopService)

	if err := app.Run(); err != nil {
		log.Fatal(err)
	}
}
