// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class CharacterAppearance {
    /**
     * Creates a new CharacterAppearance instance.
     * @param {Partial<CharacterAppearance>} [$$source = {}] - The source object to create the CharacterAppearance.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VisualManifest | null | undefined}
             */
            this["visual"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharacterAppearance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CharacterAppearance}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("visual" in $$parsedSource) {
            $$parsedSource["visual"] = $$createField1_0($$parsedSource["visual"]);
        }
        return new CharacterAppearance(/** @type {Partial<CharacterAppearance>} */($$parsedSource));
    }
}

export class CharacterRecord {
    /**
     * Creates a new CharacterRecord instance.
     * @param {Partial<CharacterRecord>} [$$source = {}] - The source object to create the CharacterRecord.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["characterId"] = "";
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {CharacterAppearance}
             */
            this["appearance"] = (new CharacterAppearance());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharacterRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CharacterRecord}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField3_0($$parsedSource["appearance"]);
        }
        return new CharacterRecord(/** @type {Partial<CharacterRecord>} */($$parsedSource));
    }
}

export class MessageRecord {
    /**
     * Creates a new MessageRecord instance.
     * @param {Partial<MessageRecord>} [$$source = {}] - The source object to create the MessageRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("turnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["turnId"] = "";
        }
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageRecord(/** @type {Partial<MessageRecord>} */($$parsedSource));
    }
}

export class VisualAnchor {
    /**
     * Creates a new VisualAnchor instance.
     * @param {Partial<VisualAnchor>} [$$source = {}] - The source object to create the VisualAnchor.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VisualAnchor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VisualAnchor}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VisualAnchor(/** @type {Partial<VisualAnchor>} */($$parsedSource));
    }
}

export class VisualFrame {
    /**
     * Creates a new VisualFrame instance.
     * @param {Partial<VisualFrame>} [$$source = {}] - The source object to create the VisualFrame.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VisualFrame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VisualFrame}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VisualFrame(/** @type {Partial<VisualFrame>} */($$parsedSource));
    }
}

export class VisualManifest {
    /**
     * Creates a new VisualManifest instance.
     * @param {Partial<VisualManifest>} [$$source = {}] - The source object to create the VisualManifest.
     */
    constructor($$source = {}) {
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("packId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["packId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("renderer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["renderer"] = "";
        }
        if (!("frame" in $$source)) {
            /**
             * @member
             * @type {VisualFrame}
             */
            this["frame"] = (new VisualFrame());
        }
        if (!("scale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scale"] = 0;
        }
        if (!("anchor" in $$source)) {
            /**
             * @member
             * @type {VisualAnchor}
             */
            this["anchor"] = (new VisualAnchor());
        }
        if (!("states" in $$source)) {
            /**
             * @member
             * @type {VisualState[]}
             */
            this["states"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VisualManifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VisualManifest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField4_0($$parsedSource["frame"]);
        }
        if ("anchor" in $$parsedSource) {
            $$parsedSource["anchor"] = $$createField6_0($$parsedSource["anchor"]);
        }
        if ("states" in $$parsedSource) {
            $$parsedSource["states"] = $$createField7_0($$parsedSource["states"]);
        }
        return new VisualManifest(/** @type {Partial<VisualManifest>} */($$parsedSource));
    }
}

export class VisualState {
    /**
     * Creates a new VisualState instance.
     * @param {Partial<VisualState>} [$$source = {}] - The source object to create the VisualState.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("imagePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imagePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VisualState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VisualState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VisualState(/** @type {Partial<VisualState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = VisualManifest.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = CharacterAppearance.createFrom;
const $$createType3 = VisualFrame.createFrom;
const $$createType4 = VisualAnchor.createFrom;
const $$createType5 = VisualState.createFrom;
const $$createType6 = $Create.Array($$createType5);
