// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const AuthRequirement = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AuthRequirementBearerKey: "bearer_key_required",
    AuthRequirementNone: "none",
};

export class CompiledPromptRequest {
    /**
     * Creates a new CompiledPromptRequest instance.
     * @param {Partial<CompiledPromptRequest>} [$$source = {}] - The source object to create the CompiledPromptRequest.
     */
    constructor($$source = {}) {
        if (!("shape" in $$source)) {
            /**
             * @member
             * @type {ModelRequestShape}
             */
            this["shape"] = (new ModelRequestShape());
        }
        if (!("input" in $$source)) {
            /**
             * @member
             * @type {PromptItem[]}
             */
            this["input"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["previousResponseId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompiledPromptRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompiledPromptRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shape" in $$parsedSource) {
            $$parsedSource["shape"] = $$createField0_0($$parsedSource["shape"]);
        }
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField1_0($$parsedSource["input"]);
        }
        return new CompiledPromptRequest(/** @type {Partial<CompiledPromptRequest>} */($$parsedSource));
    }
}

export class ModelRequestShape {
    /**
     * Creates a new ModelRequestShape instance.
     * @param {Partial<ModelRequestShape>} [$$source = {}] - The source object to create the ModelRequestShape.
     */
    constructor($$source = {}) {
        if (!("lane" in $$source)) {
            /**
             * @member
             * @type {PromptLane}
             */
            this["lane"] = PromptLane.$zero;
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("instructions" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instructions"] = "";
        }
        if (!("maxOutputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxOutputTokens"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["promptCacheKey"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelRequestShape instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelRequestShape}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelRequestShape(/** @type {Partial<ModelRequestShape>} */($$parsedSource));
    }
}

export class PromptItem {
    /**
     * Creates a new PromptItem instance.
     * @param {Partial<PromptItem>} [$$source = {}] - The source object to create the PromptItem.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {PromptItemType}
             */
            this["type"] = PromptItemType.$zero;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromptItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptItem(/** @type {Partial<PromptItem>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const PromptItemType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PromptItemUserMessage: "user_message",
    PromptItemAssistantMessage: "assistant_message",
    PromptItemContextData: "context_data",
};

/**
 * @readonly
 * @enum {string}
 */
export const PromptLane = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PromptLaneRespond: "respond",
    PromptLaneCompact: "compact",
    PromptLaneExtract: "extract",
};

/**
 * @readonly
 * @enum {string}
 */
export const Protocol = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ProtocolResponses: "responses",
    ProtocolChatCompletions: "chat_completions",
};

export class RequestDraft {
    /**
     * Creates a new RequestDraft instance.
     * @param {Partial<RequestDraft>} [$$source = {}] - The source object to create the RequestDraft.
     */
    constructor($$source = {}) {
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {Protocol}
             */
            this["protocol"] = Protocol.$zero;
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (!("authRequirement" in $$source)) {
            /**
             * @member
             * @type {AuthRequirement}
             */
            this["authRequirement"] = AuthRequirement.$zero;
        }
        if (!("bodyJSON" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyJSON"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestDraft instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RequestDraft}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestDraft(/** @type {Partial<RequestDraft>} */($$parsedSource));
    }
}

export class StreamEvent {
    /**
     * Creates a new StreamEvent instance.
     * @param {Partial<StreamEvent>} [$$source = {}] - The source object to create the StreamEvent.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["data"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Usage | null | undefined}
             */
            this["usage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StreamEvent}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField2_0($$parsedSource["usage"]);
        }
        return new StreamEvent(/** @type {Partial<StreamEvent>} */($$parsedSource));
    }
}

export class Usage {
    /**
     * Creates a new Usage instance.
     * @param {Partial<Usage>} [$$source = {}] - The source object to create the Usage.
     */
    constructor($$source = {}) {
        if (!("promptTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completionTokens"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["cachedInputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["cacheWriteTokens"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Usage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage(/** @type {Partial<Usage>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ModelRequestShape.createFrom;
const $$createType1 = PromptItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Usage.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
