// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.CompiledPromptRequest} request
 * @returns {$CancellablePromise<$models.RequestDraft>}
 */
export function BuildRequestDraft(request) {
    return $Call.ByID(228029436, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.PromptLane} lane
 * @param {string} instructions
 * @param {number} maxOutputTokens
 * @param {$models.PromptItem[]} input
 * @param {string} promptCacheKey
 * @returns {$CancellablePromise<$models.StreamEvent[]>}
 */
export function ExecutePrompt(lane, instructions, maxOutputTokens, input, promptCacheKey) {
    return $Call.ByID(2090146569, lane, instructions, maxOutputTokens, input, promptCacheKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.CompiledPromptRequest} request
 * @returns {$CancellablePromise<$models.StreamEvent[]>}
 */
export function ExecuteRequest(request) {
    return $Call.ByID(1584359028, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.CompiledPromptRequest} request
 * @returns {$CancellablePromise<$models.StreamEvent[]>}
 */
export function ExecuteRequestContext(request) {
    return $Call.ByID(3649639639, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.RequestDraft.createFrom;
const $$createType1 = $models.StreamEvent.createFrom;
const $$createType2 = $Create.Array($$createType1);
