// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../fairy/transport/session/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(1398431892);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseControlPanel() {
    return $Call.ByID(1824167319);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseHistory() {
    return $Call.ByID(2326228442);
}

/**
 * @returns {$CancellablePromise<$models.CoreSession>}
 */
export function Connect() {
    return $Call.ByID(702891500).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DisableDesktopObservation() {
    return $Call.ByID(3188836008);
}

/**
 * @param {number} intervalMinutes
 * @param {number} idleMinutes
 * @returns {$CancellablePromise<void>}
 */
export function EnableDesktopObservation(intervalMinutes, idleMinutes) {
    return $Call.ByID(1036422411, intervalMinutes, idleMinutes);
}

/**
 * HideSpeechBubble is called after the WebView finishes its local fade-out.
 * @returns {$CancellablePromise<void>}
 */
export function HideSpeechBubble() {
    return $Call.ByID(1828736602);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenControlPanel() {
    return $Call.ByID(2317584603);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenHistory() {
    return $Call.ByID(3735711446);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenManagement() {
    return $Call.ByID(2057278069);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseManagement() {
    return $Call.ByID(2333417441);
}

/**
 * @returns {$CancellablePromise<session$0.MessageRecord[]>}
 */
export function RecentMessages() {
    return $Call.ByID(983675989).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} turnID
 * @param {string} beatID
 * @param {boolean} succeeded
 * @returns {$CancellablePromise<void>}
 */
export function ReportStickerDelivery(turnID, beatID, succeeded) {
    return $Call.ByID(1500694931, turnID, beatID, succeeded);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RepositionHistory() {
    return $Call.ByID(4084182200);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RepositionSpeechBubble() {
    return $Call.ByID(2314399888);
}

/**
 * @returns {$CancellablePromise<$models.CoreSettings>}
 */
export function RuntimeInfo() {
    return $Call.ByID(1820803190).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} input
 * @returns {$CancellablePromise<void>}
 */
export function Send(input) {
    return $Call.ByID(3644580932, input);
}

/**
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetDesktopObservationPrivacy(value) {
    return $Call.ByID(2769179032, value);
}

export function ManagementOverview() {
    return $Call.ByID(4060208362);
}

export function ManagementCharacters() {
    return $Call.ByID(3548151721);
}

export function ActivateManagementCharacter(characterID, revision) {
    return $Call.ByID(3038762027, characterID, revision);
}

export function ManagementProfile() {
    return $Call.ByID(3982175326);
}

export function SaveManagementProfile(preferredName) {
    return $Call.ByID(731907285, preferredName);
}

export function ClearManagementProfile() {
    return $Call.ByID(1729818257);
}

export function ManagementModel() {
    return $Call.ByID(1334820682);
}

export function SaveManagementModel(write) {
    return $Call.ByID(1276458717, write);
}

export function ClearManagementModel() {
    return $Call.ByID(1847262929);
}

export function ManagementSemantic() {
    return $Call.ByID(1739934513);
}

export function SaveManagementSemantic(write) {
    return $Call.ByID(4208760900, write);
}

export function ClearManagementSemanticCredential() {
    return $Call.ByID(1331962937);
}

export function ManagementIntelligence() {
    return $Call.ByID(3540352306);
}

export function ManagementMemories(characterID) {
    return $Call.ByID(2297955334, characterID);
}

export function CreateManagementMemory(write) {
    return $Call.ByID(3634607786, write);
}

export function TombstoneManagementMemory(id) {
    return $Call.ByID(851241689, id);
}

export function ManagementKnowledge() {
    return $Call.ByID(3408034363);
}

export function TombstoneManagementKnowledge(id) {
    return $Call.ByID(991370506, id);
}

export function ManagementPlugins() {
    return $Call.ByID(276776827);
}

export function ManagementStickers() {
    return $Call.ByID(1355178829);
}

export function ManagementQQ() {
    return $Call.ByID(1027493703);
}

export function SaveManagementQQ(settings) {
    return $Call.ByID(20767110, settings);
}

export function ManagementConversation(conversationID, beforeSequence, limit) {
    return $Call.ByID(2239267606, conversationID, beforeSequence, limit);
}

export function ManagementTurnRuntime(conversationID, turnID) {
    return $Call.ByID(3176782082, conversationID, turnID);
}

export function ManagementMetrics() {
    return $Call.ByID(55359046);
}

export function ManagementTraces(messageID) {
    return $Call.ByID(2907625815, messageID);
}

export function ManagementTrace(traceID) {
    return $Call.ByID(1417458654, traceID);
}

export function ManagementLogs() {
    return $Call.ByID(1432029494);
}

export function SubscribeManagementLogs() {
    return $Call.ByID(3998863538);
}

export function UnsubscribeManagementLogs() {
    return $Call.ByID(1663243459);
}

export function CreateManagementBackup() {
    return $Call.ByID(1849297427);
}

export function ManagementWorkspaceState() {
    return $Call.ByID(2913384795);
}

export function SaveManagementWorkspaceState(write) {
    return $Call.ByID(2594999086, write);
}

// Private type creation functions
const $$createType0 = $models.CoreSession.createFrom;
const $$createType1 = $models.CoreSettings.createFrom;
const $$createType2 = session$0.MessageRecord.createFrom;
const $$createType3 = $Create.Array($$createType2);
