// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("preferredName" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["preferredName"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

export class Update {
    /**
     * Creates a new Update instance.
     * @param {Partial<Update>} [$$source = {}] - The source object to create the Update.
     */
    constructor($$source = {}) {
        if (!("profile" in $$source)) {
            /**
             * @member
             * @type {Snapshot | null}
             */
            this["profile"] = null;
        }
        if (!("changed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["changed"] = false;
        }
        if (!("recoveredCorruption" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recoveredCorruption"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Update instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Update}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField0_0($$parsedSource["profile"]);
        }
        return new Update(/** @type {Partial<Update>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Snapshot.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
