// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Update>}
 */
export function Clear() {
    return $Call.ByID(1624248589).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Snapshot | null>}
 */
export function Current() {
    return $Call.ByID(589735365).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ProfileStore returns the process-scoped user-profile store for sharing with
 * other composition-root consumers (e.g. companion).
 * @returns {$CancellablePromise<$models.Store | null>}
 */
export function ProfileStore() {
    return $Call.ByID(212350222).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string | null} preferredName
 * @returns {$CancellablePromise<$models.Update>}
 */
export function SetPreferredName(preferredName) {
    return $Call.ByID(3485716326, preferredName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Update.createFrom;
const $$createType1 = $models.Snapshot.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.Store.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
