// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * BootstrapStatus is returned by GET /v1/status.
 */
export class BootstrapStatus {
    /**
     * Creates a new BootstrapStatus instance.
     * @param {Partial<BootstrapStatus>} [$$source = {}] - The source object to create the BootstrapStatus.
     */
    constructor($$source = {}) {
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("coreVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["coreVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BootstrapStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BootstrapStatus(/** @type {Partial<BootstrapStatus>} */($$parsedSource));
    }
}
