// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Catalog {
    /**
     * Creates a new Catalog instance.
     * @param {Partial<Catalog>} [$$source = {}] - The source object to create the Catalog.
     */
    constructor($$source = {}) {
        if (!("visualPacks" in $$source)) {
            /**
             * @member
             * @type {Manifest[]}
             */
            this["visualPacks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Catalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Catalog}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("visualPacks" in $$parsedSource) {
            $$parsedSource["visualPacks"] = $$createField0_0($$parsedSource["visualPacks"]);
        }
        return new Catalog(/** @type {Partial<Catalog>} */($$parsedSource));
    }
}

export class Frame {
    /**
     * Creates a new Frame instance.
     * @param {Partial<Frame>} [$$source = {}] - The source object to create the Frame.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Frame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Frame}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Frame(/** @type {Partial<Frame>} */($$parsedSource));
    }
}

export class Manifest {
    /**
     * Creates a new Manifest instance.
     * @param {Partial<Manifest>} [$$source = {}] - The source object to create the Manifest.
     */
    constructor($$source = {}) {
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("packId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["packId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("renderer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["renderer"] = "";
        }
        if (!("frame" in $$source)) {
            /**
             * @member
             * @type {Frame}
             */
            this["frame"] = (new Frame());
        }
        if (!("scale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scale"] = 0;
        }
        if (!("anchor" in $$source)) {
            /**
             * @member
             * @type {Point}
             */
            this["anchor"] = (new Point());
        }
        if (!("states" in $$source)) {
            /**
             * @member
             * @type {State[]}
             */
            this["states"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manifest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField4_0($$parsedSource["frame"]);
        }
        if ("anchor" in $$parsedSource) {
            $$parsedSource["anchor"] = $$createField6_0($$parsedSource["anchor"]);
        }
        if ("states" in $$parsedSource) {
            $$parsedSource["states"] = $$createField7_0($$parsedSource["states"]);
        }
        return new Manifest(/** @type {Partial<Manifest>} */($$parsedSource));
    }
}

export class Point {
    /**
     * Creates a new Point instance.
     * @param {Partial<Point>} [$$source = {}] - The source object to create the Point.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Point instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Point}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Point(/** @type {Partial<Point>} */($$parsedSource));
    }
}

export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("imagePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imagePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Manifest.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Frame.createFrom;
const $$createType3 = Point.createFrom;
const $$createType4 = State.createFrom;
const $$createType5 = $Create.Array($$createType4);
