// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} characterID
 * @param {number} revision
 * @returns {$CancellablePromise<$models.Record>}
 */
export function ActivateCharacter(characterID, revision) {
    return $Call.ByID(2259900020, characterID, revision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CatalogStore returns the process-scoped character catalog store for sharing
 * with other composition-root consumers (e.g. companion).
 * @returns {$CancellablePromise<$models.Store | null>}
 */
export function CatalogStore() {
    return $Call.ByID(3567387032).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.Brief} brief
 * @param {string} visualPackID
 * @returns {$CancellablePromise<$models.Record>}
 */
export function CreateCharacter(brief, visualPackID) {
    return $Call.ByID(2597637771, brief, visualPackID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} characterID
 * @param {string} outputPath
 * @returns {$CancellablePromise<void>}
 */
export function ExportCharacterPackage(characterID, outputPath) {
    return $Call.ByID(1121862383, characterID, outputPath);
}

/**
 * @param {string} packagePath
 * @returns {$CancellablePromise<$models.Record>}
 */
export function ImportCharacterPackage(packagePath) {
    return $Call.ByID(1508056184, packagePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Catalog>}
 */
export function ListCharacters() {
    return $Call.ByID(3255588764).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} characterID
 * @param {string} visualPackID
 * @returns {$CancellablePromise<$models.Record>}
 */
export function SetCharacterAppearance(characterID, visualPackID) {
    return $Call.ByID(3334644421, characterID, visualPackID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} characterID
 * @param {$models.Brief} brief
 * @returns {$CancellablePromise<$models.Record>}
 */
export function UpdateCharacter(characterID, brief) {
    return $Call.ByID(3852824340, characterID, brief).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Record.createFrom;
const $$createType1 = $models.Store.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.Catalog.createFrom;
