// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as visual$0 from "../visual/models.js";

export class Appearance {
    /**
     * Creates a new Appearance instance.
     * @param {Partial<Appearance>} [$$source = {}] - The source object to create the Appearance.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bindingRevision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {visual$0.Manifest | null | undefined}
             */
            this["visual"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Appearance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Appearance}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("visual" in $$parsedSource) {
            $$parsedSource["visual"] = $$createField2_0($$parsedSource["visual"]);
        }
        return new Appearance(/** @type {Partial<Appearance>} */($$parsedSource));
    }
}

export class Brief {
    /**
     * Creates a new Brief instance.
     * @param {Partial<Brief>} [$$source = {}] - The source object to create the Brief.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["dialogueStyle"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Brief instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Brief}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Brief(/** @type {Partial<Brief>} */($$parsedSource));
    }
}

export class Catalog {
    /**
     * Creates a new Catalog instance.
     * @param {Partial<Catalog>} [$$source = {}] - The source object to create the Catalog.
     */
    constructor($$source = {}) {
        if (!("characters" in $$source)) {
            /**
             * @member
             * @type {Record[]}
             */
            this["characters"] = [];
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {Record | null}
             */
            this["active"] = null;
        }
        if (!("diagnostics" in $$source)) {
            /**
             * @member
             * @type {Diagnostic[]}
             */
            this["diagnostics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Catalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Catalog}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("characters" in $$parsedSource) {
            $$parsedSource["characters"] = $$createField0_0($$parsedSource["characters"]);
        }
        if ("active" in $$parsedSource) {
            $$parsedSource["active"] = $$createField1_0($$parsedSource["active"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField2_0($$parsedSource["diagnostics"]);
        }
        return new Catalog(/** @type {Partial<Catalog>} */($$parsedSource));
    }
}

export class Diagnostic {
    /**
     * Creates a new Diagnostic instance.
     * @param {Partial<Diagnostic>} [$$source = {}] - The source object to create the Diagnostic.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["characterId"] = null;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["revision"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostic instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Diagnostic}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Diagnostic(/** @type {Partial<Diagnostic>} */($$parsedSource));
    }
}

export class Record {
    /**
     * Creates a new Record instance.
     * @param {Partial<Record>} [$$source = {}] - The source object to create the Record.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["characterId"] = "";
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("dialogueStyle" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["dialogueStyle"] = null;
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {Appearance}
             */
            this["appearance"] = (new Appearance());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Record}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField5_0($$parsedSource["appearance"]);
        }
        return new Record(/** @type {Partial<Record>} */($$parsedSource));
    }
}

export class Store {
    /**
     * Creates a new Store instance.
     * @param {Partial<Store>} [$$source = {}] - The source object to create the Store.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Store instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Store}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Store(/** @type {Partial<Store>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = visual$0.Manifest.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Record.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Nullable($$createType2);
const $$createType5 = Diagnostic.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Appearance.createFrom;
