// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @param {string} characterID
 * @returns {$CancellablePromise<$models.PersonalMemoryRecord>}
 */
export function AssignLegacyRelationship(id, characterID) {
    return $Call.ByID(976007530, id, characterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.KnowledgeRecord>}
 */
export function ConfirmKnowledgeCandidate(id) {
    return $Call.ByID(4094670423, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} kind
 * @param {$models.MemoryScope} scope
 * @param {string} content
 * @param {number} confidenceBasisPoints
 * @returns {$CancellablePromise<$models.PersonalMemoryRecord>}
 */
export function CreatePersonalMemory(kind, scope, content, confidenceBasisPoints) {
    return $Call.ByID(2768802457, kind, scope, content, confidenceBasisPoints).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} characterID
 * @returns {$CancellablePromise<$models.ExtractionBatchCatalog>}
 */
export function ExtractionBatchCatalog(characterID) {
    return $Call.ByID(1559604880, characterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.KnowledgeCatalog>}
 */
export function KnowledgeCatalog() {
    return $Call.ByID(3745516645).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} characterID
 * @returns {$CancellablePromise<$models.ConversationBootstrap>}
 */
export function OpenOrCreateCharacterConversation(characterID) {
    return $Call.ByID(25396245, characterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} characterID
 * @returns {$CancellablePromise<$models.PersonalMemoryCatalog>}
 */
export function PersonalMemoryCatalog(characterID) {
    return $Call.ByID(2366993704, characterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RetryExtractionBatch(id) {
    return $Call.ByID(1712687, id);
}

/**
 * @param {string} id
 * @param {string} content
 * @param {number} confidenceBasisPoints
 * @returns {$CancellablePromise<$models.PersonalMemoryRecord>}
 */
export function RevisePersonalMemory(id, content, confidenceBasisPoints) {
    return $Call.ByID(2495789489, id, content, confidenceBasisPoints).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SemanticEmbeddingReadiness>}
 */
export function SemanticEmbeddingStatus() {
    return $Call.ByID(658162449).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Summary>}
 */
export function Summary() {
    return $Call.ByID(3540947350).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UsageReport>}
 */
export function TokenUsageReport() {
    return $Call.ByID(92611580).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function TombstoneKnowledge(id) {
    return $Call.ByID(4287352535, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function TombstonePersonalMemory(id) {
    return $Call.ByID(4271020426, id);
}

// Private type creation functions
const $$createType0 = $models.PersonalMemoryRecord.createFrom;
const $$createType1 = $models.KnowledgeRecord.createFrom;
const $$createType2 = $models.ExtractionBatchCatalog.createFrom;
const $$createType3 = $models.KnowledgeCatalog.createFrom;
const $$createType4 = $models.ConversationBootstrap.createFrom;
const $$createType5 = $models.PersonalMemoryCatalog.createFrom;
const $$createType6 = $models.SemanticEmbeddingReadiness.createFrom;
const $$createType7 = $models.Summary.createFrom;
const $$createType8 = $models.UsageReport.createFrom;
