// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AssistantSource {
    /**
     * Creates a new AssistantSource instance.
     * @param {Partial<AssistantSource>} [$$source = {}] - The source object to create the AssistantSource.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (!("rank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rank"] = 0;
        }
        if (!("fetchedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fetchedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssistantSource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssistantSource}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssistantSource(/** @type {Partial<AssistantSource>} */($$parsedSource));
    }
}

export class CompactionResult {
    /**
     * Creates a new CompactionResult instance.
     * @param {Partial<CompactionResult>} [$$source = {}] - The source object to create the CompactionResult.
     */
    constructor($$source = {}) {
        if (!("windowRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowRevision"] = 0;
        }
        if (!("retainedDialogueItems" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retainedDialogueItems"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompactionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompactionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompactionResult(/** @type {Partial<CompactionResult>} */($$parsedSource));
    }
}

export class ConversationBootstrap {
    /**
     * Creates a new ConversationBootstrap instance.
     * @param {Partial<ConversationBootstrap>} [$$source = {}] - The source object to create the ConversationBootstrap.
     */
    constructor($$source = {}) {
        if (!("conversation" in $$source)) {
            /**
             * @member
             * @type {ConversationRecord}
             */
            this["conversation"] = (new ConversationRecord());
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {MessageRecord[]}
             */
            this["messages"] = [];
        }
        if (!("promptWindow" in $$source)) {
            /**
             * @member
             * @type {PromptWindowRecord}
             */
            this["promptWindow"] = (new PromptWindowRecord());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationBootstrap instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConversationBootstrap}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conversation" in $$parsedSource) {
            $$parsedSource["conversation"] = $$createField0_0($$parsedSource["conversation"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField1_0($$parsedSource["messages"]);
        }
        if ("promptWindow" in $$parsedSource) {
            $$parsedSource["promptWindow"] = $$createField2_0($$parsedSource["promptWindow"]);
        }
        return new ConversationBootstrap(/** @type {Partial<ConversationBootstrap>} */($$parsedSource));
    }
}

export class ConversationRecord {
    /**
     * Creates a new ConversationRecord instance.
     * @param {Partial<ConversationRecord>} [$$source = {}] - The source object to create the ConversationRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["characterId"] = "";
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }
        if (!("updatedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConversationRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConversationRecord(/** @type {Partial<ConversationRecord>} */($$parsedSource));
    }
}

export class ExtractionBatchCatalog {
    /**
     * Creates a new ExtractionBatchCatalog instance.
     * @param {Partial<ExtractionBatchCatalog>} [$$source = {}] - The source object to create the ExtractionBatchCatalog.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {ExtractionBatchRecord[]}
             */
            this["running"] = [];
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {ExtractionBatchRecord[]}
             */
            this["failed"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtractionBatchCatalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExtractionBatchCatalog}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("running" in $$parsedSource) {
            $$parsedSource["running"] = $$createField0_0($$parsedSource["running"]);
        }
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField1_0($$parsedSource["failed"]);
        }
        return new ExtractionBatchCatalog(/** @type {Partial<ExtractionBatchCatalog>} */($$parsedSource));
    }
}

export class ExtractionBatchRecord {
    /**
     * Creates a new ExtractionBatchRecord instance.
     * @param {Partial<ExtractionBatchRecord>} [$$source = {}] - The source object to create the ExtractionBatchRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["characterId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("firstTurnSequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["firstTurnSequence"] = 0;
        }
        if (!("lastTurnSequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastTurnSequence"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {WireError | null}
             */
            this["error"] = null;
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }
        if (!("updatedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtractionBatchRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExtractionBatchRecord}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField6_0($$parsedSource["error"]);
        }
        return new ExtractionBatchRecord(/** @type {Partial<ExtractionBatchRecord>} */($$parsedSource));
    }
}

export class KnowledgeCatalog {
    /**
     * Creates a new KnowledgeCatalog instance.
     * @param {Partial<KnowledgeCatalog>} [$$source = {}] - The source object to create the KnowledgeCatalog.
     */
    constructor($$source = {}) {
        if (!("candidates" in $$source)) {
            /**
             * @member
             * @type {KnowledgeRecord[]}
             */
            this["candidates"] = [];
        }
        if (!("verified" in $$source)) {
            /**
             * @member
             * @type {KnowledgeRecord[]}
             */
            this["verified"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeCatalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnowledgeCatalog}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField0_0($$parsedSource["candidates"]);
        }
        if ("verified" in $$parsedSource) {
            $$parsedSource["verified"] = $$createField1_0($$parsedSource["verified"]);
        }
        return new KnowledgeCatalog(/** @type {Partial<KnowledgeCatalog>} */($$parsedSource));
    }
}

export class KnowledgeRecord {
    /**
     * Creates a new KnowledgeRecord instance.
     * @param {Partial<KnowledgeRecord>} [$$source = {}] - The source object to create the KnowledgeRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("topic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["topic"] = "";
        }
        if (!("statement" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statement"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("verificationBasis" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["verificationBasis"] = "";
        }
        if (!("confidenceBasisPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidenceBasisPoints"] = 0;
        }
        if (!("sourceConversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceConversationId"] = "";
        }
        if (!("sourceTurnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTurnId"] = "";
        }
        if (!("supersedesId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["supersedesId"] = null;
        }
        if (!("sources" in $$source)) {
            /**
             * @member
             * @type {AssistantSource[]}
             */
            this["sources"] = [];
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }
        if (!("updatedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnowledgeRecord}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField9_0($$parsedSource["sources"]);
        }
        return new KnowledgeRecord(/** @type {Partial<KnowledgeRecord>} */($$parsedSource));
    }
}

export class MemoryScope {
    /**
     * Creates a new MemoryScope instance.
     * @param {Partial<MemoryScope>} [$$source = {}] - The source object to create the MemoryScope.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["characterId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryScope instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryScope}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryScope(/** @type {Partial<MemoryScope>} */($$parsedSource));
    }
}

export class MessageRecord {
    /**
     * Creates a new MessageRecord instance.
     * @param {Partial<MessageRecord>} [$$source = {}] - The source object to create the MessageRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("turnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["turnId"] = "";
        }
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageRecord(/** @type {Partial<MessageRecord>} */($$parsedSource));
    }
}

export class PersonalMemoryCatalog {
    /**
     * Creates a new PersonalMemoryCatalog instance.
     * @param {Partial<PersonalMemoryCatalog>} [$$source = {}] - The source object to create the PersonalMemoryCatalog.
     */
    constructor($$source = {}) {
        if (!("global" in $$source)) {
            /**
             * @member
             * @type {PersonalMemoryRecord[]}
             */
            this["global"] = [];
        }
        if (!("character" in $$source)) {
            /**
             * @member
             * @type {PersonalMemoryRecord[]}
             */
            this["character"] = [];
        }
        if (!("needsReview" in $$source)) {
            /**
             * @member
             * @type {PersonalMemoryRecord[]}
             */
            this["needsReview"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PersonalMemoryCatalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PersonalMemoryCatalog}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("global" in $$parsedSource) {
            $$parsedSource["global"] = $$createField0_0($$parsedSource["global"]);
        }
        if ("character" in $$parsedSource) {
            $$parsedSource["character"] = $$createField1_0($$parsedSource["character"]);
        }
        if ("needsReview" in $$parsedSource) {
            $$parsedSource["needsReview"] = $$createField2_0($$parsedSource["needsReview"]);
        }
        return new PersonalMemoryCatalog(/** @type {Partial<PersonalMemoryCatalog>} */($$parsedSource));
    }
}

export class PersonalMemoryRecord {
    /**
     * Creates a new PersonalMemoryRecord instance.
     * @param {Partial<PersonalMemoryRecord>} [$$source = {}] - The source object to create the PersonalMemoryRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {MemoryScope}
             */
            this["scope"] = (new MemoryScope());
        }
        if (!("reviewStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reviewStatus"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("confidenceBasisPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidenceBasisPoints"] = 0;
        }
        if (!("sourceConversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceConversationId"] = "";
        }
        if (!("sourceTurnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTurnId"] = "";
        }
        if (!("supersedesId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["supersedesId"] = null;
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }
        if (!("updatedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PersonalMemoryRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PersonalMemoryRecord}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField2_0($$parsedSource["scope"]);
        }
        return new PersonalMemoryRecord(/** @type {Partial<PersonalMemoryRecord>} */($$parsedSource));
    }
}

export class PromptWindowRecord {
    /**
     * Creates a new PromptWindowRecord instance.
     * @param {Partial<PromptWindowRecord>} [$$source = {}] - The source object to create the PromptWindowRecord.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["summary"] = null;
        }
        if (!("cutoffMessageSequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cutoffMessageSequence"] = 0;
        }
        if (!("updatedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptWindowRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromptWindowRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptWindowRecord(/** @type {Partial<PromptWindowRecord>} */($$parsedSource));
    }
}

/**
 * SemanticEmbeddingReadiness reports local semantic embedding readiness without
 * creating directories, downloading assets, or loading ONNX runtime.
 */
export class SemanticEmbeddingReadiness {
    /**
     * Creates a new SemanticEmbeddingReadiness instance.
     * @param {Partial<SemanticEmbeddingReadiness>} [$$source = {}] - The source object to create the SemanticEmbeddingReadiness.
     */
    constructor($$source = {}) {
        if (!("modelId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelId"] = "";
        }
        if (!("dimensions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dimensions"] = 0;
        }
        if (!("modelPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelPath"] = "";
        }
        if (!("modelDataPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelDataPath"] = "";
        }
        if (!("tokenizerPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tokenizerPath"] = "";
        }
        if (!("modelStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelStatus"] = "";
        }
        if (!("modelDataStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelDataStatus"] = "";
        }
        if (!("tokenizerStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tokenizerStatus"] = "";
        }
        if (!("runtimeStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runtimeStatus"] = "";
        }
        if (!("databaseStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databaseStatus"] = "";
        }
        if (!("semanticStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["semanticStatus"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("pendingJobs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pendingJobs"] = 0;
        }
        if (!("runningJobs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["runningJobs"] = 0;
        }
        if (!("failedJobs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failedJobs"] = 0;
        }
        if (!("embeddedItems" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["embeddedItems"] = 0;
        }
        if (!("vectorRows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vectorRows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SemanticEmbeddingReadiness instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SemanticEmbeddingReadiness}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SemanticEmbeddingReadiness(/** @type {Partial<SemanticEmbeddingReadiness>} */($$parsedSource));
    }
}

export class Summary {
    /**
     * Creates a new Summary instance.
     * @param {Partial<Summary>} [$$source = {}] - The source object to create the Summary.
     */
    constructor($$source = {}) {
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("conversations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conversations"] = 0;
        }
        if (!("activeGlobalMemories" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeGlobalMemories"] = 0;
        }
        if (!("activeCharacterMemories" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeCharacterMemories"] = 0;
        }
        if (!("needsReviewMemories" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["needsReviewMemories"] = 0;
        }
        if (!("pendingExtractionTurns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pendingExtractionTurns"] = 0;
        }
        if (!("runningBatches" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["runningBatches"] = 0;
        }
        if (!("failedBatches" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failedBatches"] = 0;
        }
        if (!("candidateKnowledge" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["candidateKnowledge"] = 0;
        }
        if (!("verifiedKnowledge" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verifiedKnowledge"] = 0;
        }
        if (!("readOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["readOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Summary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Summary(/** @type {Partial<Summary>} */($$parsedSource));
    }
}

/**
 * UsageLaneAggregate sums token usage for a single prompt lane. Cache figures
 * only reflect observations the provider actually returned; unobserved calls do
 * not inflate hit rates.
 */
export class UsageLaneAggregate {
    /**
     * Creates a new UsageLaneAggregate instance.
     * @param {Partial<UsageLaneAggregate>} [$$source = {}] - The source object to create the UsageLaneAggregate.
     */
    constructor($$source = {}) {
        if (!("lane" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lane"] = "";
        }
        if (!("inputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inputTokens"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outputTokens"] = 0;
        }
        if (!("cachedInputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cachedInputTokens"] = 0;
        }
        if (!("cachedObservedInputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cachedObservedInputTokens"] = 0;
        }
        if (!("cacheWriteTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cacheWriteTokens"] = 0;
        }
        if (!("callCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["callCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageLaneAggregate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageLaneAggregate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageLaneAggregate(/** @type {Partial<UsageLaneAggregate>} */($$parsedSource));
    }
}

/**
 * UsageReport is the read-only token usage rollup surfaced to the control panel.
 */
export class UsageReport {
    /**
     * Creates a new UsageReport instance.
     * @param {Partial<UsageReport>} [$$source = {}] - The source object to create the UsageReport.
     */
    constructor($$source = {}) {
        if (!("overall" in $$source)) {
            /**
             * @member
             * @type {UsageLaneAggregate[]}
             */
            this["overall"] = [];
        }
        if (!("turns" in $$source)) {
            /**
             * @member
             * @type {UsageTurn[]}
             */
            this["turns"] = [];
        }
        if (!("turnCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["turnCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageReport}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("overall" in $$parsedSource) {
            $$parsedSource["overall"] = $$createField0_0($$parsedSource["overall"]);
        }
        if ("turns" in $$parsedSource) {
            $$parsedSource["turns"] = $$createField1_0($$parsedSource["turns"]);
        }
        return new UsageReport(/** @type {Partial<UsageReport>} */($$parsedSource));
    }
}

/**
 * UsageTurn is one user send (a conversation turn) with its per-lane usage.
 */
export class UsageTurn {
    /**
     * Creates a new UsageTurn instance.
     * @param {Partial<UsageTurn>} [$$source = {}] - The source object to create the UsageTurn.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("turnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["turnId"] = "";
        }
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["characterId"] = "";
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("lanes" in $$source)) {
            /**
             * @member
             * @type {UsageLaneAggregate[]}
             */
            this["lanes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageTurn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageTurn}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lanes" in $$parsedSource) {
            $$parsedSource["lanes"] = $$createField5_0($$parsedSource["lanes"]);
        }
        return new UsageTurn(/** @type {Partial<UsageTurn>} */($$parsedSource));
    }
}

export class WireError {
    /**
     * Creates a new WireError instance.
     * @param {Partial<WireError>} [$$source = {}] - The source object to create the WireError.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("retryable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["retryable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WireError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WireError}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WireError(/** @type {Partial<WireError>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ConversationRecord.createFrom;
const $$createType1 = MessageRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = PromptWindowRecord.createFrom;
const $$createType4 = ExtractionBatchRecord.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = WireError.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = KnowledgeRecord.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = AssistantSource.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = PersonalMemoryRecord.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = MemoryScope.createFrom;
const $$createType15 = UsageLaneAggregate.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = UsageTurn.createFrom;
const $$createType18 = $Create.Array($$createType17);
