// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function CloseCompanionChat() {
    return $Call.ByID(2390084824).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExpandCompanionForSpeech shows and positions the standalone speech-bubble
 * window above the character. It is a no-op unless the companion is idle so the
 * bubble never appears over the chat or control panel.
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function ExpandCompanionForSpeech() {
    return $Call.ByID(139116139).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function GetDesktopState() {
    return $Call.ByID(4202160065).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function HideCompanion() {
    return $Call.ByID(3693982322).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function MarkTrayReady() {
    return $Call.ByID(3280294712).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function OpenCompanionChat() {
    return $Call.ByID(1047256020).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RepositionSpeechBubble keeps the bubble window glued to the character while it
 * is dragged. It is invoked from the companion window's move hook and is a no-op
 * unless the bubble is currently shown.
 * @returns {$CancellablePromise<void>}
 */
export function RepositionSpeechBubble() {
    return $Call.ByID(1782573626);
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function RestoreCompanionAfterControlPanel() {
    return $Call.ByID(3859867995).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RestoreCompanionAfterSpeech hides the standalone speech-bubble window. It is a
 * no-op when the bubble is not currently shown.
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function RestoreCompanionAfterSpeech() {
    return $Call.ByID(1140294260).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function RestoreCompanionInteraction() {
    return $Call.ByID(1804556980).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function SetAlwaysOnTop(enabled) {
    return $Call.ByID(711085763, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function SetClickThrough(enabled) {
    return $Call.ByID(3465581329, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function ShowCompanion() {
    return $Call.ByID(2665949977).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function ShowControlPanel() {
    return $Call.ByID(1384436016).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DesktopState.createFrom;
