// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BootstrapStatus {
    /**
     * Creates a new BootstrapStatus instance.
     * @param {Partial<BootstrapStatus>} [$$source = {}] - The source object to create the BootstrapStatus.
     */
    constructor($$source = {}) {
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("migrationStage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["migrationStage"] = "";
        }
        if (!("wailsVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wailsVersion"] = "";
        }
        if (!("legacyTauriPreserved" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["legacyTauriPreserved"] = false;
        }
        if (!("respondRuntimeMigrated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["respondRuntimeMigrated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BootstrapStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BootstrapStatus(/** @type {Partial<BootstrapStatus>} */($$parsedSource));
    }
}

export class DesktopState {
    /**
     * Creates a new DesktopState instance.
     * @param {Partial<DesktopState>} [$$source = {}] - The source object to create the DesktopState.
     */
    constructor($$source = {}) {
        if (!("alwaysOnTop" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysOnTop"] = false;
        }
        if (!("clickThrough" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clickThrough"] = false;
        }
        if (!("trayReady" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["trayReady"] = false;
        }
        if (!("visible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visible"] = false;
        }
        if (!("companionSurface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["companionSurface"] = "";
        }
        if (!("controlPanelVisible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["controlPanelVisible"] = false;
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopState(/** @type {Partial<DesktopState>} */($$parsedSource));
    }
}
