// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['AppService']['Cancel']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['AppService']['Connect'](arg1, arg2);
}

export function Connection(arg1, arg2) {
  return window['go']['main']['AppService']['Connection'](arg1, arg2);
}

export function SaveConnection(arg1, arg2, arg3) {
  return window['go']['main']['AppService']['SaveConnection'](arg1, arg2, arg3);
}

export function Send(arg1, arg2) {
  return window['go']['main']['AppService']['Send'](arg1, arg2);
}
