// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Cancel():Promise<void>;

export function Connect(arg1:string,arg2:string):Promise<main.SessionState>;

export function Connection(arg1:string,arg2:string):Promise<main.ConnectionState>;

export function SaveConnection(arg1:string,arg2:string,arg3:string):Promise<main.ConnectionState>;

export function Send(arg1:string,arg2:boolean):Promise<void>;
