// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Catalog {
    /**
     * Creates a new Catalog instance.
     * @param {Partial<Catalog>} [$$source = {}] - The source object to create the Catalog.
     */
    constructor($$source = {}) {
        if (!("global" in $$source)) {
            /**
             * @member
             * @type {Record[]}
             */
            this["global"] = [];
        }
        if (!("character" in $$source)) {
            /**
             * @member
             * @type {Record[]}
             */
            this["character"] = [];
        }
        if (!("needsReview" in $$source)) {
            /**
             * @member
             * @type {Record[]}
             */
            this["needsReview"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Catalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Catalog}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("global" in $$parsedSource) {
            $$parsedSource["global"] = $$createField0_0($$parsedSource["global"]);
        }
        if ("character" in $$parsedSource) {
            $$parsedSource["character"] = $$createField1_0($$parsedSource["character"]);
        }
        if ("needsReview" in $$parsedSource) {
            $$parsedSource["needsReview"] = $$createField2_0($$parsedSource["needsReview"]);
        }
        return new Catalog(/** @type {Partial<Catalog>} */($$parsedSource));
    }
}

export class Record {
    /**
     * Creates a new Record instance.
     * @param {Partial<Record>} [$$source = {}] - The source object to create the Record.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {Scope}
             */
            this["scope"] = (new Scope());
        }
        if (!("reviewStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reviewStatus"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("confidenceBasisPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidenceBasisPoints"] = 0;
        }
        if (!("sourceConversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceConversationId"] = "";
        }
        if (!("sourceTurnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTurnId"] = "";
        }
        if (!("supersedesId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["supersedesId"] = null;
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }
        if (!("updatedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Record}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField2_0($$parsedSource["scope"]);
        }
        return new Record(/** @type {Partial<Record>} */($$parsedSource));
    }
}

export class Scope {
    /**
     * Creates a new Scope instance.
     * @param {Partial<Scope>} [$$source = {}] - The source object to create the Scope.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["characterId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scope instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Scope}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Scope(/** @type {Partial<Scope>} */($$parsedSource));
    }
}

export class Summary {
    /**
     * Creates a new Summary instance.
     * @param {Partial<Summary>} [$$source = {}] - The source object to create the Summary.
     */
    constructor($$source = {}) {
        if (!("conversations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conversations"] = 0;
        }
        if (!("activeGlobalMemories" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeGlobalMemories"] = 0;
        }
        if (!("activeCharacterMemories" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeCharacterMemories"] = 0;
        }
        if (!("needsReviewMemories" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["needsReviewMemories"] = 0;
        }
        if (!("pendingExtractionTurns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pendingExtractionTurns"] = 0;
        }
        if (!("runningBatches" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["runningBatches"] = 0;
        }
        if (!("failedBatches" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failedBatches"] = 0;
        }
        if (!("readOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["readOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Summary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Summary(/** @type {Partial<Summary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Record.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Scope.createFrom;
