// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sticker$0 from "../../agent/sticker/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as character$0 from "../../context/character/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as knowledge$0 from "../../context/knowledge/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as personal$0 from "../../context/memory/personal/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../runtime/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as observability$0 from "../../runtime/observability/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../../transport/session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as web$0 from "../../transport/web/models.js";

export const CharacterCatalog = character$0.Catalog;

/**
 * @typedef {character$0.Catalog} CharacterCatalog
 */

export const CharacterRecord = character$0.Record;

/**
 * @typedef {character$0.Record} CharacterRecord
 */

export class IntelligenceSnapshot {
    /**
     * Creates a new IntelligenceSnapshot instance.
     * @param {Partial<IntelligenceSnapshot>} [$$source = {}] - The source object to create the IntelligenceSnapshot.
     */
    constructor($$source = {}) {
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {personal$0.Summary}
             */
            this["summary"] = (new personal$0.Summary());
        }
        if (!("candidateKnowledge" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["candidateKnowledge"] = 0;
        }
        if (!("verifiedKnowledge" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verifiedKnowledge"] = 0;
        }
        if (!("webSearch" in $$source)) {
            /**
             * @member
             * @type {WebSearchStatus}
             */
            this["webSearch"] = (new WebSearchStatus());
        }
        if (!("semanticEmbedding" in $$source)) {
            /**
             * @member
             * @type {SemanticStatus}
             */
            this["semanticEmbedding"] = (new SemanticStatus());
        }
        if (!("activeBackgroundJobs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeBackgroundJobs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IntelligenceSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IntelligenceSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField0_0($$parsedSource["summary"]);
        }
        if ("webSearch" in $$parsedSource) {
            $$parsedSource["webSearch"] = $$createField3_0($$parsedSource["webSearch"]);
        }
        if ("semanticEmbedding" in $$parsedSource) {
            $$parsedSource["semanticEmbedding"] = $$createField4_0($$parsedSource["semanticEmbedding"]);
        }
        return new IntelligenceSnapshot(/** @type {Partial<IntelligenceSnapshot>} */($$parsedSource));
    }
}

export const KnowledgeCatalog = knowledge$0.Catalog;

/**
 * @typedef {knowledge$0.Catalog} KnowledgeCatalog
 */

export const LogSnapshot = observability$0.LogSnapshot;

/**
 * @typedef {observability$0.LogSnapshot} LogSnapshot
 */

export const MemoryCatalog = personal$0.Catalog;

/**
 * @typedef {personal$0.Catalog} MemoryCatalog
 */

export const MemoryRecord = personal$0.Record;

/**
 * @typedef {personal$0.Record} MemoryRecord
 */

export const MemoryScope = personal$0.Scope;

/**
 * @typedef {personal$0.Scope} MemoryScope
 */

export class MemoryWrite {
    /**
     * Creates a new MemoryWrite instance.
     * @param {Partial<MemoryWrite>} [$$source = {}] - The source object to create the MemoryWrite.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {MemoryScope}
             */
            this["scope"] = (new MemoryScope());
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("confidenceBasisPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidenceBasisPoints"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryWrite instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryWrite}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField1_0($$parsedSource["scope"]);
        }
        return new MemoryWrite(/** @type {Partial<MemoryWrite>} */($$parsedSource));
    }
}

export const MessagePage = session$0.MessagePage;

/**
 * @typedef {session$0.MessagePage} MessagePage
 */

export class MetricsSnapshot {
    /**
     * Creates a new MetricsSnapshot instance.
     * @param {Partial<MetricsSnapshot>} [$$source = {}] - The source object to create the MetricsSnapshot.
     */
    constructor($$source = {}) {
        if (!("generatedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generatedAtUnixMs"] = 0;
        }
        if (!("process" in $$source)) {
            /**
             * @member
             * @type {observability$0.ProcessMetrics}
             */
            this["process"] = (new observability$0.ProcessMetrics());
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {observability$0.LogStats}
             */
            this["logs"] = (new observability$0.LogStats());
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {observability$0.MessageMetricsSnapshot}
             */
            this["messages"] = (new observability$0.MessageMetricsSnapshot());
        }
        if (!("plugins" in $$source)) {
            /**
             * @member
             * @type {observability$0.PluginMetricsSnapshot}
             */
            this["plugins"] = (new observability$0.PluginMetricsSnapshot());
        }
        if (!("history" in $$source)) {
            /**
             * @member
             * @type {observability$0.MetricHistoryPoint[]}
             */
            this["history"] = [];
        }
        if (!("historyPersistence" in $$source)) {
            /**
             * @member
             * @type {observability$0.HistoryStats}
             */
            this["historyPersistence"] = (new observability$0.HistoryStats());
        }
        if (!("activeBackgroundJobs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeBackgroundJobs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetricsSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("process" in $$parsedSource) {
            $$parsedSource["process"] = $$createField1_0($$parsedSource["process"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField2_0($$parsedSource["logs"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField3_0($$parsedSource["messages"]);
        }
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField4_0($$parsedSource["plugins"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField5_0($$parsedSource["history"]);
        }
        if ("historyPersistence" in $$parsedSource) {
            $$parsedSource["historyPersistence"] = $$createField6_0($$parsedSource["historyPersistence"]);
        }
        return new MetricsSnapshot(/** @type {Partial<MetricsSnapshot>} */($$parsedSource));
    }
}

export const ModelStatus = config$0.ModelConnectionStatus;

/**
 * @typedef {config$0.ModelConnectionStatus} ModelStatus
 */

export class ModelWrite {
    /**
     * Creates a new ModelWrite instance.
     * @param {Partial<ModelWrite>} [$$source = {}] - The source object to create the ModelWrite.
     */
    constructor($$source = {}) {
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("contextWindowTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["contextWindowTokens"] = 0;
        }
        if (!("authMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authMode"] = "";
        }
        if (!("visionInput" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visionInput"] = false;
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelWrite instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelWrite}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelWrite(/** @type {Partial<ModelWrite>} */($$parsedSource));
    }
}

export class Overview {
    /**
     * Creates a new Overview instance.
     * @param {Partial<Overview>} [$$source = {}] - The source object to create the Overview.
     */
    constructor($$source = {}) {
        if (!("bootstrap" in $$source)) {
            /**
             * @member
             * @type {core$0.BootstrapStatus}
             */
            this["bootstrap"] = (new core$0.BootstrapStatus());
        }
        if (!("configRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configRoot"] = "";
        }
        if (!("runtimeProfile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runtimeProfile"] = "";
        }
        if (!("storage" in $$source)) {
            /**
             * @member
             * @type {web$0.StorageStatus}
             */
            this["storage"] = (new web$0.StorageStatus());
        }
        if (!("secretKey" in $$source)) {
            /**
             * @member
             * @type {SecretKeyStatus}
             */
            this["secretKey"] = (new SecretKeyStatus());
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {ModelStatus}
             */
            this["model"] = (new ModelStatus());
        }
        if (!("semanticEmbedding" in $$source)) {
            /**
             * @member
             * @type {SemanticStatus}
             */
            this["semanticEmbedding"] = (new SemanticStatus());
        }
        if (!("webSearch" in $$source)) {
            /**
             * @member
             * @type {WebSearchStatus}
             */
            this["webSearch"] = (new WebSearchStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Overview}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType13;
        const $$createField5_0 = $$createType14;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bootstrap" in $$parsedSource) {
            $$parsedSource["bootstrap"] = $$createField0_0($$parsedSource["bootstrap"]);
        }
        if ("storage" in $$parsedSource) {
            $$parsedSource["storage"] = $$createField3_0($$parsedSource["storage"]);
        }
        if ("secretKey" in $$parsedSource) {
            $$parsedSource["secretKey"] = $$createField4_0($$parsedSource["secretKey"]);
        }
        if ("model" in $$parsedSource) {
            $$parsedSource["model"] = $$createField5_0($$parsedSource["model"]);
        }
        if ("semanticEmbedding" in $$parsedSource) {
            $$parsedSource["semanticEmbedding"] = $$createField6_0($$parsedSource["semanticEmbedding"]);
        }
        if ("webSearch" in $$parsedSource) {
            $$parsedSource["webSearch"] = $$createField7_0($$parsedSource["webSearch"]);
        }
        return new Overview(/** @type {Partial<Overview>} */($$parsedSource));
    }
}

export class PluginInstanceStatus {
    /**
     * Creates a new PluginInstanceStatus instance.
     * @param {Partial<PluginInstanceStatus>} [$$source = {}] - The source object to create the PluginInstanceStatus.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pluginId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lifecycle"] = undefined;
        }
        if (!("calls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["calls"] = 0;
        }
        if (!("hostCalls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hostCalls"] = 0;
        }
        if (!("budgetExceeded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["budgetExceeded"] = 0;
        }
        if (!("capabilityDenied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capabilityDenied"] = 0;
        }
        if (!("queueDepth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queueDepth"] = 0;
        }
        if (!("traps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["traps"] = 0;
        }
        if (!("restarts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["restarts"] = 0;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cancelled"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastErrorCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastTraceId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInstanceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInstanceStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginInstanceStatus(/** @type {Partial<PluginInstanceStatus>} */($$parsedSource));
    }
}

export class PluginStatus {
    /**
     * Creates a new PluginStatus instance.
     * @param {Partial<PluginStatus>} [$$source = {}] - The source object to create the PluginStatus.
     */
    constructor($$source = {}) {
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ready"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }
        if (!("metrics" in $$source)) {
            /**
             * @member
             * @type {observability$0.PluginMetricsSnapshot}
             */
            this["metrics"] = (new observability$0.PluginMetricsSnapshot());
        }
        if (!("instances" in $$source)) {
            /**
             * @member
             * @type {PluginInstanceStatus[]}
             */
            this["instances"] = [];
        }
        if (!("upgrades" in $$source)) {
            /**
             * @member
             * @type {PluginUpgradeStatus[]}
             */
            this["upgrades"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginStatus}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType16;
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField2_0($$parsedSource["metrics"]);
        }
        if ("instances" in $$parsedSource) {
            $$parsedSource["instances"] = $$createField3_0($$parsedSource["instances"]);
        }
        if ("upgrades" in $$parsedSource) {
            $$parsedSource["upgrades"] = $$createField4_0($$parsedSource["upgrades"]);
        }
        return new PluginStatus(/** @type {Partial<PluginStatus>} */($$parsedSource));
    }
}

export class PluginUpgradeStatus {
    /**
     * Creates a new PluginUpgradeStatus instance.
     * @param {Partial<PluginUpgradeStatus>} [$$source = {}] - The source object to create the PluginUpgradeStatus.
     */
    constructor($$source = {}) {
        if (!("journalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["journalId"] = "";
        }
        if (!("instanceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instanceId"] = "";
        }
        if (!("fromVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromVersion"] = "";
        }
        if (!("toVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toVersion"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorCode"] = undefined;
        }
        if (!("startedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAtUnixMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["finishedAtUnixMs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginUpgradeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginUpgradeStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginUpgradeStatus(/** @type {Partial<PluginUpgradeStatus>} */($$parsedSource));
    }
}

export const ProfileSnapshot = config$0.ProfileSnapshot;

/**
 * @typedef {config$0.ProfileSnapshot} ProfileSnapshot
 */

export const ProfileUpdate = config$0.ProfileUpdate;

/**
 * @typedef {config$0.ProfileUpdate} ProfileUpdate
 */

export class SecretKeyStatus {
    /**
     * Creates a new SecretKeyStatus instance.
     * @param {Partial<SecretKeyStatus>} [$$source = {}] - The source object to create the SecretKeyStatus.
     */
    constructor($$source = {}) {
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ready"] = false;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecretKeyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SecretKeyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecretKeyStatus(/** @type {Partial<SecretKeyStatus>} */($$parsedSource));
    }
}

export const SemanticStatus = config$0.SemanticEmbeddingStatus;

/**
 * @typedef {config$0.SemanticEmbeddingStatus} SemanticStatus
 */

export class SemanticWrite {
    /**
     * Creates a new SemanticWrite instance.
     * @param {Partial<SemanticWrite>} [$$source = {}] - The source object to create the SemanticWrite.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SemanticWrite instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SemanticWrite}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SemanticWrite(/** @type {Partial<SemanticWrite>} */($$parsedSource));
    }
}

export const StickerPage = sticker$0.Page;

/**
 * @typedef {sticker$0.Page} StickerPage
 */

export const TraceDetail = observability$0.MessageTraceDetail;

/**
 * @typedef {observability$0.MessageTraceDetail} TraceDetail
 */

export class TraceSearch {
    /**
     * Creates a new TraceSearch instance.
     * @param {Partial<TraceSearch>} [$$source = {}] - The source object to create the TraceSearch.
     */
    constructor($$source = {}) {
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("traces" in $$source)) {
            /**
             * @member
             * @type {observability$0.MessageTrace[]}
             */
            this["traces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraceSearch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TraceSearch}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("traces" in $$parsedSource) {
            $$parsedSource["traces"] = $$createField1_0($$parsedSource["traces"]);
        }
        return new TraceSearch(/** @type {Partial<TraceSearch>} */($$parsedSource));
    }
}

export class TurnRuntimeEvent {
    /**
     * Creates a new TurnRuntimeEvent instance.
     * @param {Partial<TurnRuntimeEvent>} [$$source = {}] - The source object to create the TurnRuntimeEvent.
     */
    constructor($$source = {}) {
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("eventType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventType"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["state"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["code"] = undefined;
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TurnRuntimeEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TurnRuntimeEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TurnRuntimeEvent(/** @type {Partial<TurnRuntimeEvent>} */($$parsedSource));
    }
}

export class TurnRuntimeView {
    /**
     * Creates a new TurnRuntimeView instance.
     * @param {Partial<TurnRuntimeView>} [$$source = {}] - The source object to create the TurnRuntimeView.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("turnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["turnId"] = "";
        }
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {TurnRuntimeEvent[]}
             */
            this["events"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TurnRuntimeView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TurnRuntimeView}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField2_0($$parsedSource["events"]);
        }
        return new TurnRuntimeView(/** @type {Partial<TurnRuntimeView>} */($$parsedSource));
    }
}

export const WebSearchStatus = config$0.WebSearchStatus;

/**
 * @typedef {config$0.WebSearchStatus} WebSearchStatus
 */

export class WebSearchWrite {
    /**
     * Creates a new WebSearchWrite instance.
     * @param {Partial<WebSearchWrite>} [$$source = {}] - The source object to create the WebSearchWrite.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("baseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebSearchWrite instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebSearchWrite}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebSearchWrite(/** @type {Partial<WebSearchWrite>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = personal$0.Summary.createFrom;
const $$createType1 = config$0.WebSearchStatus.createFrom;
const $$createType2 = config$0.SemanticEmbeddingStatus.createFrom;
const $$createType3 = personal$0.Scope.createFrom;
const $$createType4 = observability$0.ProcessMetrics.createFrom;
const $$createType5 = observability$0.LogStats.createFrom;
const $$createType6 = observability$0.MessageMetricsSnapshot.createFrom;
const $$createType7 = observability$0.PluginMetricsSnapshot.createFrom;
const $$createType8 = observability$0.MetricHistoryPoint.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = observability$0.HistoryStats.createFrom;
const $$createType11 = core$0.BootstrapStatus.createFrom;
const $$createType12 = web$0.StorageStatus.createFrom;
const $$createType13 = SecretKeyStatus.createFrom;
const $$createType14 = config$0.ModelConnectionStatus.createFrom;
const $$createType15 = PluginInstanceStatus.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = PluginUpgradeStatus.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = observability$0.MessageTrace.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = TurnRuntimeEvent.createFrom;
const $$createType22 = $Create.Array($$createType21);
