// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class GatewayCapabilities {
    /**
     * Creates a new GatewayCapabilities instance.
     * @param {Partial<GatewayCapabilities>} [$$source = {}] - The source object to create the GatewayCapabilities.
     */
    constructor($$source = {}) {
        if (!("promptCacheKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["promptCacheKey"] = false;
        }
        if (!("cachedTokensUsage" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cachedTokensUsage"] = false;
        }
        if (!("explicitBreakpoints" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["explicitBreakpoints"] = false;
        }
        if (!("cacheRetention" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cacheRetention"] = false;
        }
        if (!("websocketContinuation" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["websocketContinuation"] = false;
        }
        if (!("visionInput" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["visionInput"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayCapabilities instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GatewayCapabilities}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayCapabilities(/** @type {Partial<GatewayCapabilities>} */($$parsedSource));
    }
}

export class ModelConnectionStatus {
    /**
     * Creates a new ModelConnectionStatus instance.
     * @param {Partial<ModelConnectionStatus>} [$$source = {}] - The source object to create the ModelConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ready"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["contextWindowTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["authMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GatewayCapabilities | undefined}
             */
            this["capabilities"] = undefined;
        }
        if (!("credentialConfigured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["credentialConfigured"] = false;
        }
        if (!("secretStorageMigrated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secretStorageMigrated"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelConnectionStatus}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField7_0($$parsedSource["capabilities"]);
        }
        return new ModelConnectionStatus(/** @type {Partial<ModelConnectionStatus>} */($$parsedSource));
    }
}

export class ProfileSnapshot {
    /**
     * Creates a new ProfileSnapshot instance.
     * @param {Partial<ProfileSnapshot>} [$$source = {}] - The source object to create the ProfileSnapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("preferredName" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["preferredName"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSnapshot(/** @type {Partial<ProfileSnapshot>} */($$parsedSource));
    }
}

export class ProfileUpdate {
    /**
     * Creates a new ProfileUpdate instance.
     * @param {Partial<ProfileUpdate>} [$$source = {}] - The source object to create the ProfileUpdate.
     */
    constructor($$source = {}) {
        if (!("profile" in $$source)) {
            /**
             * @member
             * @type {ProfileSnapshot | null}
             */
            this["profile"] = null;
        }
        if (!("changed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["changed"] = false;
        }
        if (!("recoveredCorruption" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recoveredCorruption"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileUpdate}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField0_0($$parsedSource["profile"]);
        }
        return new ProfileUpdate(/** @type {Partial<ProfileUpdate>} */($$parsedSource));
    }
}

export class SemanticEmbeddingStatus {
    /**
     * Creates a new SemanticEmbeddingStatus instance.
     * @param {Partial<SemanticEmbeddingStatus>} [$$source = {}] - The source object to create the SemanticEmbeddingStatus.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (!("dimensions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dimensions"] = 0;
        }
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("credentialConfigured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["credentialConfigured"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SemanticEmbeddingStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SemanticEmbeddingStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SemanticEmbeddingStatus(/** @type {Partial<SemanticEmbeddingStatus>} */($$parsedSource));
    }
}

export class WebSearchStatus {
    /**
     * Creates a new WebSearchStatus instance.
     * @param {Partial<WebSearchStatus>} [$$source = {}] - The source object to create the WebSearchStatus.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ready"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebSearchStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebSearchStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebSearchStatus(/** @type {Partial<WebSearchStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = GatewayCapabilities.createFrom;
const $$createType1 = ProfileSnapshot.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
