// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class AssistantSource {
    /**
     * Creates a new AssistantSource instance.
     * @param {Partial<AssistantSource>} [$$source = {}] - The source object to create the AssistantSource.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (!("rank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rank"] = 0;
        }
        if (!("fetchedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fetchedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssistantSource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssistantSource}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssistantSource(/** @type {Partial<AssistantSource>} */($$parsedSource));
    }
}

export class Catalog {
    /**
     * Creates a new Catalog instance.
     * @param {Partial<Catalog>} [$$source = {}] - The source object to create the Catalog.
     */
    constructor($$source = {}) {
        if (!("candidates" in $$source)) {
            /**
             * @member
             * @type {Record[]}
             */
            this["candidates"] = [];
        }
        if (!("verified" in $$source)) {
            /**
             * @member
             * @type {Record[]}
             */
            this["verified"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Catalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Catalog}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField0_0($$parsedSource["candidates"]);
        }
        if ("verified" in $$parsedSource) {
            $$parsedSource["verified"] = $$createField1_0($$parsedSource["verified"]);
        }
        return new Catalog(/** @type {Partial<Catalog>} */($$parsedSource));
    }
}

export class Record {
    /**
     * Creates a new Record instance.
     * @param {Partial<Record>} [$$source = {}] - The source object to create the Record.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("topic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["topic"] = "";
        }
        if (!("statement" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statement"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("verificationBasis" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["verificationBasis"] = "";
        }
        if (!("confidenceBasisPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidenceBasisPoints"] = 0;
        }
        if (!("sourceConversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceConversationId"] = "";
        }
        if (!("sourceTurnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTurnId"] = "";
        }
        if (!("supersedesId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["supersedesId"] = null;
        }
        if (!("sources" in $$source)) {
            /**
             * @member
             * @type {AssistantSource[]}
             */
            this["sources"] = [];
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }
        if (!("updatedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Record}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField9_0($$parsedSource["sources"]);
        }
        return new Record(/** @type {Partial<Record>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Record.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = AssistantSource.createFrom;
const $$createType3 = $Create.Array($$createType2);
