// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Appearance {
    /**
     * Creates a new Appearance instance.
     * @param {Partial<Appearance>} [$$source = {}] - The source object to create the Appearance.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bindingRevision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Manifest | null | undefined}
             */
            this["visual"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Appearance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Appearance}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("visual" in $$parsedSource) {
            $$parsedSource["visual"] = $$createField2_0($$parsedSource["visual"]);
        }
        return new Appearance(/** @type {Partial<Appearance>} */($$parsedSource));
    }
}

export class Catalog {
    /**
     * Creates a new Catalog instance.
     * @param {Partial<Catalog>} [$$source = {}] - The source object to create the Catalog.
     */
    constructor($$source = {}) {
        if (!("characters" in $$source)) {
            /**
             * @member
             * @type {Record[]}
             */
            this["characters"] = [];
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {Record | null}
             */
            this["active"] = null;
        }
        if (!("diagnostics" in $$source)) {
            /**
             * @member
             * @type {Diagnostic[]}
             */
            this["diagnostics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Catalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Catalog}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("characters" in $$parsedSource) {
            $$parsedSource["characters"] = $$createField0_0($$parsedSource["characters"]);
        }
        if ("active" in $$parsedSource) {
            $$parsedSource["active"] = $$createField1_0($$parsedSource["active"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField2_0($$parsedSource["diagnostics"]);
        }
        return new Catalog(/** @type {Partial<Catalog>} */($$parsedSource));
    }
}

export class Diagnostic {
    /**
     * Creates a new Diagnostic instance.
     * @param {Partial<Diagnostic>} [$$source = {}] - The source object to create the Diagnostic.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["characterId"] = null;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["revision"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostic instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Diagnostic}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Diagnostic(/** @type {Partial<Diagnostic>} */($$parsedSource));
    }
}

export class Frame {
    /**
     * Creates a new Frame instance.
     * @param {Partial<Frame>} [$$source = {}] - The source object to create the Frame.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Frame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Frame}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Frame(/** @type {Partial<Frame>} */($$parsedSource));
    }
}

export class Manifest {
    /**
     * Creates a new Manifest instance.
     * @param {Partial<Manifest>} [$$source = {}] - The source object to create the Manifest.
     */
    constructor($$source = {}) {
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("packId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["packId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("renderer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["renderer"] = "";
        }
        if (!("frame" in $$source)) {
            /**
             * @member
             * @type {Frame}
             */
            this["frame"] = (new Frame());
        }
        if (!("scale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scale"] = 0;
        }
        if (!("anchor" in $$source)) {
            /**
             * @member
             * @type {Point}
             */
            this["anchor"] = (new Point());
        }
        if (!("states" in $$source)) {
            /**
             * @member
             * @type {State[]}
             */
            this["states"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manifest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType7;
        const $$createField6_0 = $$createType8;
        const $$createField7_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField4_0($$parsedSource["frame"]);
        }
        if ("anchor" in $$parsedSource) {
            $$parsedSource["anchor"] = $$createField6_0($$parsedSource["anchor"]);
        }
        if ("states" in $$parsedSource) {
            $$parsedSource["states"] = $$createField7_0($$parsedSource["states"]);
        }
        return new Manifest(/** @type {Partial<Manifest>} */($$parsedSource));
    }
}

export class Point {
    /**
     * Creates a new Point instance.
     * @param {Partial<Point>} [$$source = {}] - The source object to create the Point.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Point instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Point}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Point(/** @type {Partial<Point>} */($$parsedSource));
    }
}

export class Record {
    /**
     * Creates a new Record instance.
     * @param {Partial<Record>} [$$source = {}] - The source object to create the Record.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["characterId"] = "";
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("dialogueStyle" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["dialogueStyle"] = null;
        }
        if (!("textLanguage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["textLanguage"] = "";
        }
        if (!("speakingLanguage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speakingLanguage"] = "";
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {Appearance}
             */
            this["appearance"] = (new Appearance());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Record}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField7_0($$parsedSource["appearance"]);
        }
        return new Record(/** @type {Partial<Record>} */($$parsedSource));
    }
}

export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("imagePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imagePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Manifest.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Record.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Nullable($$createType2);
const $$createType5 = Diagnostic.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Frame.createFrom;
const $$createType8 = Point.createFrom;
const $$createType9 = State.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Appearance.createFrom;
