// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SaveSettingsRequest {
    /**
     * Creates a new SaveSettingsRequest instance.
     * @param {Partial<SaveSettingsRequest>} [$$source = {}] - The source object to create the SaveSettingsRequest.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("trainPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trainPath"] = "";
        }
        if (!("queryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["queryPath"] = "";
        }
        if (!("upgradePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["upgradePath"] = "";
        }
        if (!("appId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appId"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("accessToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accessToken"] = "";
        }
        if (!("clearApiKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clearApiKey"] = false;
        }
        if (!("clearAccessToken" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clearAccessToken"] = false;
        }
        if (!("defaultSpeaker" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultSpeaker"] = "";
        }
        if (!("defaultLanguage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["defaultLanguage"] = 0;
        }
        if (!("defaultFormat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultFormat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSettingsRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveSettingsRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveSettingsRequest(/** @type {Partial<SaveSettingsRequest>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("trainPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trainPath"] = "";
        }
        if (!("queryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["queryPath"] = "";
        }
        if (!("upgradePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["upgradePath"] = "";
        }
        if (!("appId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appId"] = "";
        }
        if (!("defaultSpeaker" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultSpeaker"] = "";
        }
        if (!("defaultLanguage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["defaultLanguage"] = 0;
        }
        if (!("defaultFormat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultFormat"] = "";
        }
        if (!("hasApiKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasApiKey"] = false;
        }
        if (!("hasAccessToken" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasAccessToken"] = false;
        }
        if (!("secretMigrated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secretMigrated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

export class TrainVoiceRequest {
    /**
     * Creates a new TrainVoiceRequest instance.
     * @param {Partial<TrainVoiceRequest>} [$$source = {}] - The source object to create the TrainVoiceRequest.
     */
    constructor($$source = {}) {
        if (!("speakerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speakerId"] = "";
        }
        if (!("audioData" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["audioData"] = "";
        }
        if (!("audioFormat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["audioFormat"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["language"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["extraParams"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrainVoiceRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrainVoiceRequest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extraParams" in $$parsedSource) {
            $$parsedSource["extraParams"] = $$createField4_0($$parsedSource["extraParams"]);
        }
        return new TrainVoiceRequest(/** @type {Partial<TrainVoiceRequest>} */($$parsedSource));
    }
}

export class VoiceModelStatus {
    /**
     * Creates a new VoiceModelStatus instance.
     * @param {Partial<VoiceModelStatus>} [$$source = {}] - The source object to create the VoiceModelStatus.
     */
    constructor($$source = {}) {
        if (!("modelType" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modelType"] = 0;
        }
        if (!("demoAudio" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["demoAudio"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoiceModelStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VoiceModelStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VoiceModelStatus(/** @type {Partial<VoiceModelStatus>} */($$parsedSource));
    }
}

export class VoiceOperationRequest {
    /**
     * Creates a new VoiceOperationRequest instance.
     * @param {Partial<VoiceOperationRequest>} [$$source = {}] - The source object to create the VoiceOperationRequest.
     */
    constructor($$source = {}) {
        if (!("speakerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speakerId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoiceOperationRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VoiceOperationRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VoiceOperationRequest(/** @type {Partial<VoiceOperationRequest>} */($$parsedSource));
    }
}

export class VoiceResult {
    /**
     * Creates a new VoiceResult instance.
     * @param {Partial<VoiceResult>} [$$source = {}] - The source object to create the VoiceResult.
     */
    constructor($$source = {}) {
        if (!("httpStatus" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpStatus"] = 0;
        }
        if (!("logid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logid"] = "";
        }
        if (!("speakerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speakerId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("availableTrainingTimes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["availableTrainingTimes"] = 0;
        }
        if (!("createTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createTime"] = 0;
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["language"] = 0;
        }
        if (!("speakerStatus" in $$source)) {
            /**
             * @member
             * @type {VoiceModelStatus[]}
             */
            this["speakerStatus"] = [];
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("rawJson" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rawJson"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoiceResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VoiceResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("speakerStatus" in $$parsedSource) {
            $$parsedSource["speakerStatus"] = $$createField7_0($$parsedSource["speakerStatus"]);
        }
        return new VoiceResult(/** @type {Partial<VoiceResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = VoiceModelStatus.createFrom;
const $$createType2 = $Create.Array($$createType1);
