// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ClearSettings() {
    return $Call.ByID(811768768).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.VoiceOperationRequest} request
 * @returns {$CancellablePromise<$models.VoiceResult>}
 */
export function QueryVoice(request) {
    return $Call.ByID(1211575854, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.SaveSettingsRequest} input
 * @returns {$CancellablePromise<$models.Status>}
 */
export function SaveSettings(input) {
    return $Call.ByID(368193296, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Status() {
    return $Call.ByID(3075862930).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.TrainVoiceRequest} request
 * @returns {$CancellablePromise<$models.VoiceResult>}
 */
export function TrainVoice(request) {
    return $Call.ByID(2674585748, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.VoiceOperationRequest} request
 * @returns {$CancellablePromise<$models.VoiceResult>}
 */
export function UpgradeVoice(request) {
    return $Call.ByID(3696259046, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
const $$createType1 = $models.VoiceResult.createFrom;
