// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * StorageStatus is the credential-free storage readiness projection for local
 * status and metrics. It never includes connection strings or master-key material.
 */
export class StorageStatus {
    /**
     * Creates a new StorageStatus instance.
     * @param {Partial<StorageStatus>} [$$source = {}] - The source object to create the StorageStatus.
     */
    constructor($$source = {}) {
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ready"] = false;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["storage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["descriptor"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["schema"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["secretsReady"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["openConnections"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StorageStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageStatus(/** @type {Partial<StorageStatus>} */($$parsedSource));
    }
}
