// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as memory$0 from "../memory/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<number>}
 */
export function ActiveBackgroundJobs() {
    return $Call.ByID(1279791358);
}

/**
 * CancelTurn cancels an in-flight compiled turn for the conversation.
 * @param {string} conversationID
 * @param {string} turnID
 * @returns {$CancellablePromise<void>}
 */
export function CancelTurn(conversationID, turnID) {
    return $Call.ByID(1898384805, conversationID, turnID);
}

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<memory$0.CompactionResult>}
 */
export function CompactConversation(conversationID) {
    return $Call.ByID(2604408474, conversationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function RespondRuntimeMigrated() {
    return $Call.ByID(2780690232);
}

/**
 * @param {$models.SubmitCompiledTurnRequest} request
 * @returns {$CancellablePromise<$models.TurnOutcome>}
 */
export function SubmitCompiledTurn(request) {
    return $Call.ByID(3368406068, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.SubmitTurnRequest} request
 * @returns {$CancellablePromise<$models.TurnOutcome>}
 */
export function SubmitTurn(request) {
    return $Call.ByID(2564538947, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = memory$0.CompactionResult.createFrom;
const $$createType1 = $models.TurnOutcome.createFrom;
