// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ReplyChain {
    /**
     * Creates a new ReplyChain instance.
     * @param {Partial<ReplyChain>} [$$source = {}] - The source object to create the ReplyChain.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("speechText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speechText"] = "";
        }
        if (!("visualState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["visualState"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplyChain instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReplyChain}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplyChain(/** @type {Partial<ReplyChain>} */($$parsedSource));
    }
}

export class SubmitCompiledTurnRequest {
    /**
     * Creates a new SubmitCompiledTurnRequest instance.
     * @param {Partial<SubmitCompiledTurnRequest>} [$$source = {}] - The source object to create the SubmitCompiledTurnRequest.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("input" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input"] = "";
        }
        if (!("speechEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["speechEnabled"] = false;
        }
        if (!("maxOutputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxOutputTokens"] = 0;
        }
        if (!("availableVisualStates" in $$source)) {
            /**
             * @member
             * @type {VisualState[]}
             */
            this["availableVisualStates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmitCompiledTurnRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SubmitCompiledTurnRequest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("availableVisualStates" in $$parsedSource) {
            $$parsedSource["availableVisualStates"] = $$createField4_0($$parsedSource["availableVisualStates"]);
        }
        return new SubmitCompiledTurnRequest(/** @type {Partial<SubmitCompiledTurnRequest>} */($$parsedSource));
    }
}

export class SubmitTurnRequest {
    /**
     * Creates a new SubmitTurnRequest instance.
     * @param {Partial<SubmitTurnRequest>} [$$source = {}] - The source object to create the SubmitTurnRequest.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("input" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input"] = "";
        }
        if (!("speechEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["speechEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmitTurnRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SubmitTurnRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubmitTurnRequest(/** @type {Partial<SubmitTurnRequest>} */($$parsedSource));
    }
}

export class TurnOutcome {
    /**
     * Creates a new TurnOutcome instance.
     * @param {Partial<TurnOutcome>} [$$source = {}] - The source object to create the TurnOutcome.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("turnId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["turnId"] = "";
        }
        if (!("responseText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["responseText"] = "";
        }
        if (!("speechText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speechText"] = "";
        }
        if (!("speechRequested" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["speechRequested"] = false;
        }
        if (!("visualState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["visualState"] = "";
        }
        if (!("chains" in $$source)) {
            /**
             * @member
             * @type {ReplyChain[]}
             */
            this["chains"] = [];
        }
        if (!("respondMigrated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["respondMigrated"] = false;
        }
        if (!("migrationMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["migrationMessage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TurnOutcome instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TurnOutcome}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chains" in $$parsedSource) {
            $$parsedSource["chains"] = $$createField6_0($$parsedSource["chains"]);
        }
        return new TurnOutcome(/** @type {Partial<TurnOutcome>} */($$parsedSource));
    }
}

export class VisualState {
    /**
     * Creates a new VisualState instance.
     * @param {Partial<VisualState>} [$$source = {}] - The source object to create the VisualState.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VisualState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VisualState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VisualState(/** @type {Partial<VisualState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = VisualState.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ReplyChain.createFrom;
const $$createType3 = $Create.Array($$createType2);
