package companion

const (
	SocialLearnMaxOutputTokens         uint32 = 2048
	socialLearningQueueCapacity               = 8
	socialLearningObservationThreshold        = 20
	maxSocialLearningEntries                  = 12
	maxSocialLearningSourceIDs                = 8
	maxSocialLearningPersonNotes              = 8
)

const SocialLearnInstructions = "Learn reusable public-group social context and light public peer notes from the supplied external human observations. Output exactly one strict JSON object: {\"entries\":[{\"kind\":\"episode|expression|behavior\",\"situation\":\"<abstract situation>\",\"content\":\"<concise reusable summary or pattern>\",\"recallCue\":\"<natural-language retrieval cue>\",\"sourceMessageIds\":[\"<supporting message id>\"]}],\"personNotes\":[{\"senderId\":\"<observation senderId>\",\"note\":\"<concise public habit in this group>\",\"sourceMessageIds\":[\"<supporting message id>\"]}]}. The top level may contain only entries and personNotes. entries may contain only those five fields; personNotes may contain only those three fields. Return between zero and 12 entries and between zero and 8 personNotes. Either array may be empty when evidence is insufficient. Learn only from the supplied external human messages. Do not infer private facts, personality diagnoses, protected traits, secrets, medical/psychological labels, or information not present in the evidence. episode captures public shared context, agreements, topic progress, or a group experience. expression captures a reusable situation-to-speaking-style pattern without copying a long original phrase. behavior captures a reusable situation-to-social-action-to-observed-outcome pattern only when the outcome is visible in later messages. personNotes capture only reusable public interaction habits of a sender inside this group (for example talkative, often jokes, frequently @bot). Remove names beyond senderId linkage, one-off proper nouns, screenshots, configuration values, and temporary task details from learned content. Do not quote long source passages, imitate hostility more strongly than the evidence, or turn facts into personality claims. For every entry and personNote, sourceMessageIds must contain between one and eight unique message IDs from the supplied observations, and every referenced observation must directly support that item. Each personNote.senderId must appear in the supplied observations, and at least one source message must be from that sender. Do not output reasoning, prose, Markdown, unknown fields, null fields, or trailing data."
