// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../fairy/transport/session/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(1398431892);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseControlPanel() {
    return $Call.ByID(1824167319);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseHistory() {
    return $Call.ByID(2326228442);
}

/**
 * @returns {$CancellablePromise<$models.CoreSession>}
 */
export function Connect() {
    return $Call.ByID(702891500).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DisableDesktopObservation() {
    return $Call.ByID(3188836008);
}

/**
 * @param {number} intervalMinutes
 * @param {number} idleMinutes
 * @returns {$CancellablePromise<void>}
 */
export function EnableDesktopObservation(intervalMinutes, idleMinutes) {
    return $Call.ByID(1036422411, intervalMinutes, idleMinutes);
}

/**
 * HideSpeechBubble is called after the WebView finishes its local fade-out.
 * @returns {$CancellablePromise<void>}
 */
export function HideSpeechBubble() {
    return $Call.ByID(1828736602);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenControlPanel() {
    return $Call.ByID(2317584603);
}

/**
 * OpenHistory keeps recent messages beside the pet rather than expanding or
 * covering the companion window with the retired chat surface.
 * @returns {$CancellablePromise<void>}
 */
export function OpenHistory() {
    return $Call.ByID(3735711446);
}

/**
 * @returns {$CancellablePromise<session$0.MessageRecord[]>}
 */
export function RecentMessages() {
    return $Call.ByID(983675989).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} turnID
 * @param {string} beatID
 * @param {boolean} succeeded
 * @returns {$CancellablePromise<void>}
 */
export function ReportStickerDelivery(turnID, beatID, succeeded) {
    return $Call.ByID(1500694931, turnID, beatID, succeeded);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RepositionHistory() {
    return $Call.ByID(4084182200);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RepositionSpeechBubble() {
    return $Call.ByID(2314399888);
}

/**
 * @returns {$CancellablePromise<$models.CoreSettings>}
 */
export function RuntimeInfo() {
    return $Call.ByID(1820803190).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} input
 * @returns {$CancellablePromise<void>}
 */
export function Send(input) {
    return $Call.ByID(3644580932, input);
}

/**
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetDesktopObservationPrivacy(value) {
    return $Call.ByID(2769179032, value);
}

// Private type creation functions
const $$createType0 = $models.CoreSession.createFrom;
const $$createType1 = $models.CoreSettings.createFrom;
const $$createType2 = session$0.MessageRecord.createFrom;
const $$createType3 = $Create.Array($$createType2);
