// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as coreclient$0 from "../fairy/coreclient/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(1398431892);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseControlPanel() {
    return $Call.ByID(1824167319);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseHistory() {
    return $Call.ByID(2326228442);
}

/**
 * @param {string} endpoint
 * @param {string} endpointKey
 * @returns {$CancellablePromise<$models.CoreSession>}
 */
export function Connect(endpoint, endpointKey) {
    return $Call.ByID(702891500, endpoint, endpointKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * HideSpeechBubble is called after the WebView finishes its local fade-out.
 * @returns {$CancellablePromise<void>}
 */
export function HideSpeechBubble() {
    return $Call.ByID(1828736602);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenControlPanel() {
    return $Call.ByID(2317584603);
}

/**
 * OpenHistory keeps recent messages beside the pet rather than expanding or
 * covering the companion window with the retired chat surface.
 * @returns {$CancellablePromise<void>}
 */
export function OpenHistory() {
    return $Call.ByID(3735711446);
}

/**
 * @returns {$CancellablePromise<coreclient$0.MessageRecord[]>}
 */
export function RecentMessages() {
    return $Call.ByID(983675989).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RepositionHistory() {
    return $Call.ByID(4084182200);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RepositionSpeechBubble() {
    return $Call.ByID(2314399888);
}

/**
 * @param {string} endpoint
 * @param {string} token
 * @param {string} endpointKey
 * @returns {$CancellablePromise<$models.CoreSettings>}
 */
export function SaveConnection(endpoint, token, endpointKey) {
    return $Call.ByID(3874272299, endpoint, token, endpointKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} input
 * @param {boolean} speechEnabled
 * @returns {$CancellablePromise<void>}
 */
export function Send(input, speechEnabled) {
    return $Call.ByID(3644580932, input, speechEnabled);
}

// Private type creation functions
const $$createType0 = $models.CoreSession.createFrom;
const $$createType1 = coreclient$0.MessageRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.CoreSettings.createFrom;
