// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as coreclient$0 from "../fairy/coreclient/models.js";

export class CoreSession {
    /**
     * Creates a new CoreSession instance.
     * @param {Partial<CoreSession>} [$$source = {}] - The source object to create the CoreSession.
     */
    constructor($$source = {}) {
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {CoreSettings}
             */
            this["settings"] = (new CoreSettings());
        }
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("character" in $$source)) {
            /**
             * @member
             * @type {coreclient$0.CharacterRecord}
             */
            this["character"] = (new coreclient$0.CharacterRecord());
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {coreclient$0.MessageRecord[]}
             */
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CoreSession}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        if ("character" in $$parsedSource) {
            $$parsedSource["character"] = $$createField2_0($$parsedSource["character"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField3_0($$parsedSource["messages"]);
        }
        return new CoreSession(/** @type {Partial<CoreSession>} */($$parsedSource));
    }
}

export class CoreSettings {
    /**
     * Creates a new CoreSettings instance.
     * @param {Partial<CoreSettings>} [$$source = {}] - The source object to create the CoreSettings.
     */
    constructor($$source = {}) {
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("endpointKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpointKey"] = "";
        }
        if (!("hasToken" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasToken"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CoreSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoreSettings(/** @type {Partial<CoreSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = CoreSettings.createFrom;
const $$createType1 = coreclient$0.CharacterRecord.createFrom;
const $$createType2 = coreclient$0.MessageRecord.createFrom;
const $$createType3 = $Create.Array($$createType2);
