// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.ModelConnectionStatus>}
 */
export function ClearModelConnection() {
    return $Call.ByID(3860415162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ModelConnectionStatus>}
 */
export function ModelStatus() {
    return $Call.ByID(518621123).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.ModelConnectionInput} input
 * @param {string | null} apiKey
 * @returns {$CancellablePromise<$models.ModelConnectionStatus>}
 */
export function SaveModelConnection(input, apiKey) {
    return $Call.ByID(2882342562, input, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.WebSearchStatus>}
 */
export function SetWebSearchEnabled(enabled) {
    return $Call.ByID(2014502367, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.WebSearchStatus>}
 */
export function WebSearchStatus() {
    return $Call.ByID(2401839252).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ModelConnectionStatus.createFrom;
const $$createType1 = $models.WebSearchStatus.createFrom;
