// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GatewayCapabilities {
    /**
     * Creates a new GatewayCapabilities instance.
     * @param {Partial<GatewayCapabilities>} [$$source = {}] - The source object to create the GatewayCapabilities.
     */
    constructor($$source = {}) {
        if (!("promptCacheKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["promptCacheKey"] = false;
        }
        if (!("cachedTokensUsage" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cachedTokensUsage"] = false;
        }
        if (!("explicitBreakpoints" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["explicitBreakpoints"] = false;
        }
        if (!("cacheRetention" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cacheRetention"] = false;
        }
        if (!("websocketContinuation" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["websocketContinuation"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayCapabilities instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GatewayCapabilities}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayCapabilities(/** @type {Partial<GatewayCapabilities>} */($$parsedSource));
    }
}

export class ModelConnectionInput {
    /**
     * Creates a new ModelConnectionInput instance.
     * @param {Partial<ModelConnectionInput>} [$$source = {}] - The source object to create the ModelConnectionInput.
     */
    constructor($$source = {}) {
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("contextWindowTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["contextWindowTokens"] = 0;
        }
        if (!("authMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelConnectionInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelConnectionInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelConnectionInput(/** @type {Partial<ModelConnectionInput>} */($$parsedSource));
    }
}

export class ModelConnectionStatus {
    /**
     * Creates a new ModelConnectionStatus instance.
     * @param {Partial<ModelConnectionStatus>} [$$source = {}] - The source object to create the ModelConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["contextWindowTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["authMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GatewayCapabilities | undefined}
             */
            this["capabilities"] = undefined;
        }
        if (!("secretStorageMigrated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secretStorageMigrated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelConnectionStatus}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField6_0($$parsedSource["capabilities"]);
        }
        return new ModelConnectionStatus(/** @type {Partial<ModelConnectionStatus>} */($$parsedSource));
    }
}

export class WebSearchStatus {
    /**
     * Creates a new WebSearchStatus instance.
     * @param {Partial<WebSearchStatus>} [$$source = {}] - The source object to create the WebSearchStatus.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("binaryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["binaryPath"] = "";
        }
        if (!("binaryFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["binaryFound"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebSearchStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebSearchStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebSearchStatus(/** @type {Partial<WebSearchStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = GatewayCapabilities.createFrom;
