// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * HistoryStats exposes the bounded persistence queue health without exposing
 * the concrete database-backed Store.
 */
export class HistoryStats {
    /**
     * Creates a new HistoryStats instance.
     * @param {Partial<HistoryStats>} [$$source = {}] - The source object to create the HistoryStats.
     */
    constructor($$source = {}) {
        if (!("queued" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queued"] = 0;
        }
        if (!("queueDropped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queueDropped"] = 0;
        }
        if (!("writeFailed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["writeFailed"] = 0;
        }
        if (!("cleanupFailed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cleanupFailed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryStats(/** @type {Partial<HistoryStats>} */($$parsedSource));
    }
}

/**
 * LogEntry is the only log record shape exposed over HTTP and the CLI.
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequence"] = 0;
        }
        if (!("timestampUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestampUnixMs"] = 0;
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("logger" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logger"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("messageTruncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["messageTruncated"] = false;
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {LogField[]}
             */
            this["fields"] = [];
        }
        if (!("fieldsTruncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fieldsTruncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField6_0($$parsedSource["fields"]);
        }
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * LogField is the bounded public representation of a structured zap field.
 */
export class LogField {
    /**
     * Creates a new LogField instance.
     * @param {Partial<LogField>} [$$source = {}] - The source object to create the LogField.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogField}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogField(/** @type {Partial<LogField>} */($$parsedSource));
    }
}

/**
 * LogSnapshot contains a deterministic query result and store counters.
 */
export class LogSnapshot {
    /**
     * Creates a new LogSnapshot instance.
     * @param {Partial<LogSnapshot>} [$$source = {}] - The source object to create the LogSnapshot.
     */
    constructor($$source = {}) {
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {LogEntry[]}
             */
            this["entries"] = [];
        }
        if (!("retainedEntries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retainedEntries"] = 0;
        }
        if (!("droppedEntries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["droppedEntries"] = 0;
        }
        if (!("latestSequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latestSequence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new LogSnapshot(/** @type {Partial<LogSnapshot>} */($$parsedSource));
    }
}

/**
 * LogStats is embedded in the runtime metrics response.
 */
export class LogStats {
    /**
     * Creates a new LogStats instance.
     * @param {Partial<LogStats>} [$$source = {}] - The source object to create the LogStats.
     */
    constructor($$source = {}) {
        if (!("retainedEntries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retainedEntries"] = 0;
        }
        if (!("droppedEntries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["droppedEntries"] = 0;
        }
        if (!("activeSubscribers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeSubscribers"] = 0;
        }
        if (!("slowSubscriberDisconnects" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["slowSubscriberDisconnects"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogStats(/** @type {Partial<LogStats>} */($$parsedSource));
    }
}

export class MessageLatencyMetrics {
    /**
     * Creates a new MessageLatencyMetrics instance.
     * @param {Partial<MessageLatencyMetrics>} [$$source = {}] - The source object to create the MessageLatencyMetrics.
     */
    constructor($$source = {}) {
        if (!("observations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["observations"] = 0;
        }
        if (!("totalDurationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalDurationMs"] = 0;
        }
        if (!("maxDurationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxDurationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageLatencyMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageLatencyMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageLatencyMetrics(/** @type {Partial<MessageLatencyMetrics>} */($$parsedSource));
    }
}

export class MessageLatencySnapshot {
    /**
     * Creates a new MessageLatencySnapshot instance.
     * @param {Partial<MessageLatencySnapshot>} [$$source = {}] - The source object to create the MessageLatencySnapshot.
     */
    constructor($$source = {}) {
        if (!("receiveToDecision" in $$source)) {
            /**
             * @member
             * @type {MessageLatencyMetrics}
             */
            this["receiveToDecision"] = (new MessageLatencyMetrics());
        }
        if (!("receiveToTurn" in $$source)) {
            /**
             * @member
             * @type {MessageLatencyMetrics}
             */
            this["receiveToTurn"] = (new MessageLatencyMetrics());
        }
        if (!("turnToFirstBeat" in $$source)) {
            /**
             * @member
             * @type {MessageLatencyMetrics}
             */
            this["turnToFirstBeat"] = (new MessageLatencyMetrics());
        }
        if (!("turnToCompleted" in $$source)) {
            /**
             * @member
             * @type {MessageLatencyMetrics}
             */
            this["turnToCompleted"] = (new MessageLatencyMetrics());
        }
        if (!("receiveToFirstBeat" in $$source)) {
            /**
             * @member
             * @type {MessageLatencyMetrics}
             */
            this["receiveToFirstBeat"] = (new MessageLatencyMetrics());
        }
        if (!("receiveToCompleted" in $$source)) {
            /**
             * @member
             * @type {MessageLatencyMetrics}
             */
            this["receiveToCompleted"] = (new MessageLatencyMetrics());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageLatencySnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageLatencySnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("receiveToDecision" in $$parsedSource) {
            $$parsedSource["receiveToDecision"] = $$createField0_0($$parsedSource["receiveToDecision"]);
        }
        if ("receiveToTurn" in $$parsedSource) {
            $$parsedSource["receiveToTurn"] = $$createField1_0($$parsedSource["receiveToTurn"]);
        }
        if ("turnToFirstBeat" in $$parsedSource) {
            $$parsedSource["turnToFirstBeat"] = $$createField2_0($$parsedSource["turnToFirstBeat"]);
        }
        if ("turnToCompleted" in $$parsedSource) {
            $$parsedSource["turnToCompleted"] = $$createField3_0($$parsedSource["turnToCompleted"]);
        }
        if ("receiveToFirstBeat" in $$parsedSource) {
            $$parsedSource["receiveToFirstBeat"] = $$createField4_0($$parsedSource["receiveToFirstBeat"]);
        }
        if ("receiveToCompleted" in $$parsedSource) {
            $$parsedSource["receiveToCompleted"] = $$createField5_0($$parsedSource["receiveToCompleted"]);
        }
        return new MessageLatencySnapshot(/** @type {Partial<MessageLatencySnapshot>} */($$parsedSource));
    }
}

export class MessageMetricsSnapshot {
    /**
     * Creates a new MessageMetricsSnapshot instance.
     * @param {Partial<MessageMetricsSnapshot>} [$$source = {}] - The source object to create the MessageMetricsSnapshot.
     */
    constructor($$source = {}) {
        if (!("received" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["received"] = 0;
        }
        if (!("sent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sent"] = 0;
        }
        if (!("directReceived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["directReceived"] = 0;
        }
        if (!("ambientReceived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ambientReceived"] = 0;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("interrupted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interrupted"] = 0;
        }
        if (!("silent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["silent"] = 0;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["active"] = 0;
        }
        if (!("droppedEvents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["droppedEvents"] = 0;
        }
        if (!("latencies" in $$source)) {
            /**
             * @member
             * @type {MessageLatencySnapshot}
             */
            this["latencies"] = (new MessageLatencySnapshot());
        }
        if (!("recent" in $$source)) {
            /**
             * @member
             * @type {MessageTrace[]}
             */
            this["recent"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageMetricsSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageMetricsSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType5;
        const $$createField11_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("latencies" in $$parsedSource) {
            $$parsedSource["latencies"] = $$createField10_0($$parsedSource["latencies"]);
        }
        if ("recent" in $$parsedSource) {
            $$parsedSource["recent"] = $$createField11_0($$parsedSource["recent"]);
        }
        return new MessageMetricsSnapshot(/** @type {Partial<MessageMetricsSnapshot>} */($$parsedSource));
    }
}

export class MessageTrace {
    /**
     * Creates a new MessageTrace instance.
     * @param {Partial<MessageTrace>} [$$source = {}] - The source object to create the MessageTrace.
     */
    constructor($$source = {}) {
        if (!("traceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["traceId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["messageId"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["turnId"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("receivedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["receivedAtUnixMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["decisionAtUnixMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["turnStartedAtUnixMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["firstBeatAtUnixMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["completedAtUnixMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["totalDurationMs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageTrace instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageTrace}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageTrace(/** @type {Partial<MessageTrace>} */($$parsedSource));
    }
}

export class MessageTraceDetail {
    /**
     * Creates a new MessageTraceDetail instance.
     * @param {Partial<MessageTraceDetail>} [$$source = {}] - The source object to create the MessageTraceDetail.
     */
    constructor($$source = {}) {
        if (!("traceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["traceId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["messageId"] = undefined;
        }
        if (!("conversationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["turnId"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("startedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAtUnixMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["endedAtUnixMs"] = undefined;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("droppedSpanCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["droppedSpanCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("spans" in $$source)) {
            /**
             * @member
             * @type {TraceSpan[]}
             */
            this["spans"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageTraceDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageTraceDetail}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("spans" in $$parsedSource) {
            $$parsedSource["spans"] = $$createField11_0($$parsedSource["spans"]);
        }
        return new MessageTraceDetail(/** @type {Partial<MessageTraceDetail>} */($$parsedSource));
    }
}

/**
 * MetricHistoryPoint is the public metric snapshot persisted by Core and
 * returned by the observability API.
 */
export class MetricHistoryPoint {
    /**
     * Creates a new MetricHistoryPoint instance.
     * @param {Partial<MetricHistoryPoint>} [$$source = {}] - The source object to create the MetricHistoryPoint.
     */
    constructor($$source = {}) {
        if (!("timestampUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestampUnixMs"] = 0;
        }
        if (!("processStartedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["processStartedAtUnixMs"] = 0;
        }
        if (!("httpScope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["httpScope"] = "";
        }
        if (!("httpTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpTotal"] = 0;
        }
        if (!("httpInFlight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpInFlight"] = 0;
        }
        if (!("httpStatus4xx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpStatus4xx"] = 0;
        }
        if (!("httpStatus5xx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpStatus5xx"] = 0;
        }
        if (!("messagesReceived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["messagesReceived"] = 0;
        }
        if (!("messagesSent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["messagesSent"] = 0;
        }
        if (!("messagesActive" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["messagesActive"] = 0;
        }
        if (!("messagesFailed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["messagesFailed"] = 0;
        }
        if (!("inputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inputTokens"] = 0;
        }
        if (!("cachedInputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cachedInputTokens"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outputTokens"] = 0;
        }
        if (!("modelCalls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modelCalls"] = 0;
        }
        if (!("learningEnqueued" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningEnqueued"] = 0;
        }
        if (!("learningSucceeded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningSucceeded"] = 0;
        }
        if (!("learningFailed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningFailed"] = 0;
        }
        if (!("learningDropped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningDropped"] = 0;
        }
        if (!("learningModelCalls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningModelCalls"] = 0;
        }
        if (!("learningInputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningInputTokens"] = 0;
        }
        if (!("learningCachedObservedInputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningCachedObservedInputTokens"] = 0;
        }
        if (!("learningCachedInputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningCachedInputTokens"] = 0;
        }
        if (!("learningCacheWriteTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningCacheWriteTokens"] = 0;
        }
        if (!("learningOutputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["learningOutputTokens"] = 0;
        }
        if (!("feedbackRegistered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackRegistered"] = 0;
        }
        if (!("feedbackSuperseded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackSuperseded"] = 0;
        }
        if (!("feedbackSucceeded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackSucceeded"] = 0;
        }
        if (!("feedbackFailed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackFailed"] = 0;
        }
        if (!("feedbackDropped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackDropped"] = 0;
        }
        if (!("feedbackModelCalls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackModelCalls"] = 0;
        }
        if (!("feedbackInputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackInputTokens"] = 0;
        }
        if (!("feedbackCachedObservedInputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackCachedObservedInputTokens"] = 0;
        }
        if (!("feedbackCachedInputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackCachedInputTokens"] = 0;
        }
        if (!("feedbackCacheWriteTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackCacheWriteTokens"] = 0;
        }
        if (!("feedbackOutputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedbackOutputTokens"] = 0;
        }
        if (!("compactionL1Applied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["compactionL1Applied"] = 0;
        }
        if (!("compactionL2Applied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["compactionL2Applied"] = 0;
        }
        if (!("compactionL3Applied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["compactionL3Applied"] = 0;
        }
        if (!("compactionFailed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["compactionFailed"] = 0;
        }
        if (!("goroutines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["goroutines"] = 0;
        }
        if (!("backgroundJobs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backgroundJobs"] = 0;
        }
        if (!("eventSubscribers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["eventSubscribers"] = 0;
        }
        if (!("logSubscribers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["logSubscribers"] = 0;
        }
        if (!("heapMiB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["heapMiB"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricHistoryPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetricHistoryPoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricHistoryPoint(/** @type {Partial<MetricHistoryPoint>} */($$parsedSource));
    }
}

/**
 * PluginInstanceMetrics is the public per-instance diagnostic projection.
 */
export class PluginInstanceMetrics {
    /**
     * Creates a new PluginInstanceMetrics instance.
     * @param {Partial<PluginInstanceMetrics>} [$$source = {}] - The source object to create the PluginInstanceMetrics.
     */
    constructor($$source = {}) {
        if (!("instanceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instanceId"] = "";
        }
        if (!("calls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["calls"] = 0;
        }
        if (!("hostCalls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hostCalls"] = 0;
        }
        if (!("budgetExceeded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["budgetExceeded"] = 0;
        }
        if (!("capabilityDenied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capabilityDenied"] = 0;
        }
        if (!("traps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["traps"] = 0;
        }
        if (!("restarts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["restarts"] = 0;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cancelled"] = 0;
        }
        if (!("queueDepth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queueDepth"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastErrorCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastTraceId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInstanceMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInstanceMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginInstanceMetrics(/** @type {Partial<PluginInstanceMetrics>} */($$parsedSource));
    }
}

/**
 * PluginMetricsSnapshot is the host-wide plugin diagnostic projection.
 */
export class PluginMetricsSnapshot {
    /**
     * Creates a new PluginMetricsSnapshot instance.
     * @param {Partial<PluginMetricsSnapshot>} [$$source = {}] - The source object to create the PluginMetricsSnapshot.
     */
    constructor($$source = {}) {
        if (!("calls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["calls"] = 0;
        }
        if (!("hostCalls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hostCalls"] = 0;
        }
        if (!("inFlight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inFlight"] = 0;
        }
        if (!("queueWaiters" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queueWaiters"] = 0;
        }
        if (!("budgetExceeded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["budgetExceeded"] = 0;
        }
        if (!("capabilityDenied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capabilityDenied"] = 0;
        }
        if (!("traps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["traps"] = 0;
        }
        if (!("restarts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["restarts"] = 0;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cancelled"] = 0;
        }
        if (!("instances" in $$source)) {
            /**
             * @member
             * @type {PluginInstanceMetrics[]}
             */
            this["instances"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginMetricsSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginMetricsSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("instances" in $$parsedSource) {
            $$parsedSource["instances"] = $$createField9_0($$parsedSource["instances"]);
        }
        return new PluginMetricsSnapshot(/** @type {Partial<PluginMetricsSnapshot>} */($$parsedSource));
    }
}

export class ProcessMetrics {
    /**
     * Creates a new ProcessMetrics instance.
     * @param {Partial<ProcessMetrics>} [$$source = {}] - The source object to create the ProcessMetrics.
     */
    constructor($$source = {}) {
        if (!("uptimeSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uptimeSeconds"] = 0;
        }
        if (!("goVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goVersion"] = "";
        }
        if (!("goroutines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["goroutines"] = 0;
        }
        if (!("heapAllocBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["heapAllocBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessMetrics(/** @type {Partial<ProcessMetrics>} */($$parsedSource));
    }
}

export class TraceSpan {
    /**
     * Creates a new TraceSpan instance.
     * @param {Partial<TraceSpan>} [$$source = {}] - The source object to create the TraceSpan.
     */
    constructor($$source = {}) {
        if (!("spanId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["spanId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentSpanId"] = undefined;
        }
        if (!("operation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operation"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("startedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAtUnixMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["endedAtUnixMs"] = undefined;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("attributes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraceSpan instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TraceSpan}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField8_0($$parsedSource["attributes"]);
        }
        return new TraceSpan(/** @type {Partial<TraceSpan>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = LogField.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = LogEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = MessageLatencyMetrics.createFrom;
const $$createType5 = MessageLatencySnapshot.createFrom;
const $$createType6 = MessageTrace.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = TraceSpan.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = PluginInstanceMetrics.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Map($Create.Any, $Create.Any);
