// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Page {
    /**
     * Creates a new Page instance.
     * @param {Partial<Page>} [$$source = {}] - The source object to create the Page.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {Record[]}
             */
            this["items"] = [];
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["nextOffset"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Page instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Page}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new Page(/** @type {Partial<Page>} */($$parsedSource));
    }
}

export class Record {
    /**
     * Creates a new Record instance.
     * @param {Partial<Record>} [$$source = {}] - The source object to create the Record.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("contentSha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentSha256"] = "";
        }
        if (!("mimeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mimeType"] = "";
        }
        if (!("byteCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["byteCount"] = 0;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = Status.$zero;
        }
        if (!("createdAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAtUnixMs"] = 0;
        }
        if (!("updatedAtUnixMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAtUnixMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Record}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new Record(/** @type {Partial<Record>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusDraft: "draft",
    StatusActive: "active",
    StatusDisabled: "disabled",
};

// Private type creation functions
const $$createType0 = Record.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
